unpackaged/main/default/objects/Account/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <description>Unique ID used for Tax Free merchants.</description>
    <externalId>true</externalId>
    <inlineHelpText>HO: 
2-letter country code + TRS or AX number for HO 
_____________________________
Store: 
2-letter country code + S + TRS or AX number for Shops + S for Single Sale + P for PTF</inlineHelpText>
    <label>Account ID</label>
    <length>64</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/External_Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>External_Passport_Number__c</fullName>
    <externalId>true</externalId>
    <label>External Passport Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/External_Premier_Pass_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Premier_Pass_ID__c</fullName>
    <externalId>true</externalId>
    <label>External Premier Pass ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Owning_Country__c.field-meta.xml
<CustomField>
    <fullName>Owning_Country__c</fullName>
    <defaultValue>IF($User.Country = &quot;United Kingdom&quot;, &quot;United Kingdom&quot;,
IF($User.Country = &quot;Austria&quot;, &quot;Austria&quot;,
IF($User.Country = &quot;Belgium&quot;, &quot;Belgium&quot;,
IF($User.Country = &quot;Colombia&quot;, &quot;Colombia&quot;,
IF($User.Country = &quot;Czech Republic&quot;, &quot;Czech Republic&quot;,
IF($User.Country = &quot;Denmark&quot;, &quot;Denmark&quot;,
IF($User.Country = &quot;Finland&quot;, &quot;Finland&quot;,
IF($User.Country = &quot;France&quot;, &quot;France&quot;,
IF($User.Country = &quot;Germany&quot;, &quot;Germany&quot;,
IF($User.Country = &quot;Greece&quot;, &quot;Greece&quot;,
IF($User.Country = &quot;Hong Kong&quot;, &quot;Hong Kong&quot;,
IF($User.Country = &quot;Hungary&quot;, &quot;Hungary&quot;,
IF($User.Country = &quot;Iceland&quot;, &quot;Iceland&quot;,
IF($User.Country = &quot;Ireland&quot;, &quot;Ireland&quot;,
IF($User.Country = &quot;Italy&quot;, &quot;Italy&quot;,
IF($User.Country = &quot;Korea, Republic of&quot;, &quot;Korea, Republic of&quot;,
IF($User.Country = &quot;Poland&quot;, &quot;Poland&quot;,
IF($User.Country = &quot;Portugal&quot;, &quot;Portugal&quot;,
IF($User.Country = &quot;Singapore&quot;, &quot;Singapore&quot;,
IF($User.Country = &quot;Spain&quot;, &quot;Spain&quot;,
IF($User.Country = &quot;Sweden&quot;, &quot;Sweden&quot;,
IF($User.Country = &quot;United States&quot;, &quot;United States&quot;,
IF($User.Country = &quot;Canada&quot;, &quot;Canada&quot;,
IF($User.Country = &quot;Turkey&quot;, &quot;Turkey&quot;,
IF($User.Country = &quot;Switzerland&quot;, &quot;&quot;, null)))))))))))))))))))))))))</defaultValue>
    <label>Owning Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company_Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Person_Email_External__c.field-meta.xml
<CustomField>
    <fullName>Person_Email_External__c</fullName>
    <externalId>true</externalId>
    <label>Person Email External</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Premier_Pass_ID__c.field-meta.xml
<CustomField>
    <fullName>Premier_Pass_ID__c</fullName>
    <description>To hold TFF Premier Pass ID</description>
    <label>Premier Pass ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fintrax_API_Endpoint_URLs__c/Fintrax_API_Endpoint_URLs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Fintrax API Endpoint URLs</label>
</CustomObject>

unpackaged/main/default/objects/Fintrax_API_Endpoint_URLs__c/fields/Search_EndPoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Search_EndPoint_URL__c</fullName>
    <label>Search EndPoint URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Fintrax_API_Endpoint_URLs__c/fields/Sync_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Sync_Endpoint_URL__c</fullName>
    <label>Sync Endpoint URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Fintrax_TFF_Search_Fields__c/Fintrax_TFF_Search_Fields__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Fintrax TFF Search Fields</label>
</CustomObject>

unpackaged/main/default/objects/Fintrax_TFF_Search_Fields__c/fields/Fintrax_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Fintrax_Field_API_Name__c</fullName>
    <label>Fintrax Field API Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fintrax_TFF_Search_Fields__c/fields/SF_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SF_Field_API_Name__c</fullName>
    <label>SF Field API Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/Tax_Free_Form__c.object-meta.xml
<CustomObject>
    <label>Tax Free Form</label>
    <nameField>
        <label>Tax Free Form Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Free Form</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Account_Shop__c.field-meta.xml
<CustomField>
    <fullName>Account_Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Shop</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tax Free Form</relationshipLabel>
    <relationshipName>Tax_Free_Form</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Alipay_Id__c.field-meta.xml
<CustomField>
    <fullName>Alipay_Id__c</fullName>
    <label>Alipay Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <label>Cheque Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Country_Of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Country_Of_Purchase__c</fullName>
    <label>Country Of Purchase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Credit_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Number__c</fullName>
    <label>Credit Card Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Customs_Date_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Customs_Date_Stamp__c</fullName>
    <label>Customs Date Stamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/ExternalId_Tax_Free_Form_Id__c.field-meta.xml
<CustomField>
    <fullName>ExternalId_Tax_Free_Form_Id__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId Tax Free Form Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Latest_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Latest_Payment_Status__c</fullName>
    <label>Latest Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Masked_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Masked_Card_Number__c</fullName>
    <label>Masked Card Number</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/P2_Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>P2_Entry_Date__c</fullName>
    <label>P2 Entry Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Qualified_Date__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Date__c</fullName>
    <label>Qualified Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Refund_Currency__c.field-meta.xml
<CustomField>
    <fullName>Refund_Currency__c</fullName>
    <label>Refund Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Refund_Date__c.field-meta.xml
<CustomField>
    <fullName>Refund_Date__c</fullName>
    <label>Refund Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Refund_Method__c.field-meta.xml
<CustomField>
    <fullName>Refund_Method__c</fullName>
    <label>Refund Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Retailer_Id__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Id__c</fullName>
    <label>Retailer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Sales_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sales_Amount__c</fullName>
    <label>Sales Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Sales_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sales_Currency__c</fullName>
    <label>Sales Currency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Tourist__c.field-meta.xml
<CustomField>
    <fullName>Tourist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tourist</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tourist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tax Free Form (Tourist)</relationshipLabel>
    <relationshipName>Tourist</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Tourist_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Tourist_Email_Address__c</fullName>
    <label>Tourist Email Address</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Tourist_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Tourist_First_Name__c</fullName>
    <label>Tourist First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Tourist_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Tourist_Last_Name__c</fullName>
    <label>Tourist Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Tourist_Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Tourist_Passport_Number__c</fullName>
    <label>Tourist Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Tourist_Premier_Pass_Id__c.field-meta.xml
<CustomField>
    <fullName>Tourist_Premier_Pass_Id__c</fullName>
    <label>Tourist Premier Pass Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Vendor_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Number__c</fullName>
    <label>Vendor Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Tax_Free_Form_Search_Ctrl.cls
global class Tax_Free_Form_Search_Ctrl {
    public list<Tax_Free_Form__c> SFRecordsList { get; set; }
    public string searchField {get;set;}
    public string searchTerm {get;set;}
    public Boolean sfdcSearchTable {get;set;}
    public Boolean fintraxSearchTable {get;set;}
    public integer sfsearchsize {get;set;}
    public integer fintraxsearchsize {get;set;}
    public list<TFFFintraxObj> FinRecordlist {set;get;}
    public string tfid;
    public string selectedTFFids {get;set;}
    Public Tax_Free_Form_Search_Ctrl (ApexPages.StandardController controller){
        sfdcSearchTable = false;
        fintraxSearchTable = false;
        SFRecordsList = new list<Tax_Free_Form__c>();
        FinRecordlist = new list<TFFFintraxObj>();
        fintraxsearchsize = 1;
        Tax_Free_Form__c tff  =  (Tax_Free_Form__c) controller.getRecord();
        tfid= tff.id;
    }
    Map<string, Fintrax_TFF_Search_Fields__c> FintraxTFFSeachfields= Fintrax_TFF_Search_Fields__c.getAll();
    //List<Fintrax_TFF_Search_Fields__c> FintraxTFFSeachfields= [SELECT Order__c, Name FROM Fintrax_TFF_Search_Fields__c order by Order__c];
    public List<SelectOption> getFieldOptions() {
        List<SelectOption> fieldOptions= new List<SelectOption>();
        for(Fintrax_TFF_Search_Fields__c s: [SELECT Order__c, Name FROM Fintrax_TFF_Search_Fields__c order by Order__c]){
            fieldOptions.add(new SelectOption(s.Name,s.Name));
        }
        return fieldOptions;
    }
    Public void sfSearch(){
        System.debug('searchTerm.....'+searchTerm);
        System.debug('searchField.....'+searchField);
        String sfdcQueryString ;
        sfdcQueryString ='select Id,Name,Sales_Amount__c,Refund_Amount__c,Retailer_ID__c,Tourist__r.firstname,Tourist__r.name,Tourist_Passport_Number__c,'+
            'Tourist_Premier_Pass_Id__c,Tourist_First_Name__c,Tourist_Last_Name__c,Latest_Payment_Status__c,Tourist_Email_Address__c,'+
            ' Credit_Card_Number__c,Account_shop__r.Name,Purchase_Date__c from Tax_Free_Form__c Where Id!=null ';
        if(!String.isBlank(searchTerm))  
            sfdcQueryString +='And '+FintraxTFFSeachfields.get(searchField).SF_Field_API_Name__c+' like \'%' + searchTerm + '%\'';    
        System.debug('sfdcQueryString.....'+sfdcQueryString);
        SFRecordsList = database.Query(sfdcQueryString); 
        sfsearchsize = SFRecordsList.size();
        
        System.debug('SFRecordslist size.....'+sfsearchsize );
        if(SFRecordsList.size() > 0){
            sfdcSearchTable = true;
            
            System.debug('sfdcSearchTable.....'+sfdcSearchTable);
        }else{
            sfdcSearchTable = false;
            
        }
    }
    public void fintrax_API_Search() {
        Fintrax_API_Endpoint_URLs__c FAE = Fintrax_API_Endpoint_URLs__c.getOrgDefaults();
        String EndpointURL = FAE.Search_EndPoint_URL__c+FintraxTFFSeachfields.get(searchField).Fintrax_Field_API_Name__c+'/'+searchTerm+'/';
        System.debug('@@@@@@EndpointURL@@@@@'+EndpointURL);
        list<TFFFintraxObj> TFFsearchresultlist = new list<TFFFintraxObj>();
        FinRecordlist = new list<TFFFintraxObj>();
        HttpResponse res = new HttpResponse();
        res  = FintraxWebServiceHelper.fetchHttpResponse(EndpointURL);
        System.debug('@@@@@resTest'+res);
        if (res!=null) {
            
            TFFsearchresultlist = TFFFintraxObj.jsonparse(res.getBody());
            system.debug('TFFsearchresultlist---'+TFFsearchresultlist);
            system.debug('TFFsearchresultlist--size---'+TFFsearchresultlist.size());
            if(TFFsearchresultlist.size()<=20 && TFFsearchresultlist.size()>0 ){
                FinRecordlist.addall(TFFsearchresultlist);
                fintraxsearchsize = FinRecordlist.size(); // to hold fintrax serch size , can remove after api connection 
                fintraxSearchTable = true;
            }
            else fintraxSearchTable = false;
            fintraxsearchsize = TFFsearchresultlist.size();
        }
        
        else {
            fintraxsearchsize = TFFsearchresultlist.size();
            fintraxSearchTable = false;
        }
    }
    
    public   pagereference  fintrax_API_Sync() {
        Tax_Free_Form__c TFF = new Tax_Free_Form__c(); 
        string Tffid = [select id,name from Tax_Free_Form__c where id =:tfid].name;
        Fintrax_API_Endpoint_URLs__c FAE = Fintrax_API_Endpoint_URLs__c.getOrgDefaults();
        String EndpointURL = FAE.Sync_Endpoint_URL__c+TFFid+'/';
        list<TFFFintraxObj> TFFsyncrec = new list<TFFFintraxObj>();
        HttpResponse res = new HttpResponse();
        res  = FintraxWebServiceHelper.fetchHttpResponse(EndpointURL);
        if (res !=null) {
            
            TFFsyncrec =TFFFintraxObj.jsonparse(res.getBody());
            if(TFFsyncrec.size()>0){
                
                map<string,account> accountmap = new map<string,account>();
                account insertTac = new account();
                Tax_Free_Form__c tffrecord = new Tax_Free_Form__c(); 
                string Recordtypeid = [select Id from RecordType where (Name='Tourist') and (SobjectType='Account')].id;
                
                for(account a:[select id,Account_ID__c,PersonEmail from account where Account_ID__c =: TFFsyncrec[0].RetailerId   Or PersonEmail!=null]){
                    if(a.Account_ID__c!=null) accountmap.put(a.Account_ID__c,a);
                    
                }
                tffrecord = [select id ,Name,Tourist__c from Tax_Free_Form__c where Name = : TFFid];
                Schema.SObjectField ExtID_Field = Tax_Free_Form__c.Fields.ExternalId_Tax_Free_Form_Id__c;
                Schema.SObjectField ExtEmail_Field = account.Fields.Person_Email_External__c;
                try{
                    if(tffrecord.Tourist__c==null && ((String.isNotBlank(TFFsyncrec[0].TouristFirstName))||
                                                      (String.isNotBlank(TFFsyncrec[0].TouristLastName) )) ){
                                                          
                                                          insertTac.firstname =  TFFsyncrec[0].TouristFirstName;
                                                          //Tac.lastname = 'last';
                                                          insertTac.lastname =  ((TFFsyncrec[0].TouristLastName!=''&&TFFsyncrec[0].TouristLastName!=null)?TFFsyncrec[0].TouristLastName:TFFsyncrec[0].TouristFirstName);
                                                          insertTac.PersonMailingStreet = TFFsyncrec[0].TouristAddress;
                                                          insertTac.PersonEmail = TFFsyncrec[0].TouristEmailAddress;
                                                          insertTac.Person_Email_External__c = TFFsyncrec[0].TouristEmailAddress;
                                                          insertTac.PersonBirthdate = (TFFsyncrec[0].TouristDateOfBirth!=null?date.valueof(TFFsyncrec[0].TouristDateOfBirth):null);
                                                          insertTac.PersonMobilePhone = TFFsyncrec[0].TouristPhoneNumber;
                                                          insertTac.PersonMailingPostalCode = TFFsyncrec[0].TouristPostalCode;
                                                          insertTac.Owning_Country__c = TFFsyncrec[0].CountryOfPurchase ;
                                                          insertTac.RecordTypeId = Recordtypeid;
                                                          insertTac.Passport_Number__c = TFFsyncrec[0].TouristPassportNumber ;
                                                          insertTac.Premier_Pass_ID__c = TFFsyncrec[0].TouristPremierPassId ;
                                                          insertTac.External_Passport_Number__c = TFFsyncrec[0].TouristPassportNumber ;
                                                          insertTac.External_Premier_Pass_ID__c = TFFsyncrec[0].TouristPremierPassId ;
                                                          insert insertTac;
                                                      }else if((String.isNotBlank(TFFsyncrec[0].TouristFirstName))||
                                                               (String.isNotBlank(TFFsyncrec[0].TouristLastName) )){
                                                                   account updateTac = new account();
                                                                   updateTac.id = tffrecord.Tourist__c;
                                                                   updateTac.firstname =  TFFsyncrec[0].TouristFirstName;
                                                                   //Tac.lastname = 'last';
                                                                   updateTac.lastname =  ((TFFsyncrec[0].TouristLastName!=''&&TFFsyncrec[0].TouristLastName!=null)?TFFsyncrec[0].TouristLastName:TFFsyncrec[0].TouristFirstName);
                                                                   updateTac.PersonMailingStreet = TFFsyncrec[0].TouristAddress;
                                                                   updateTac.PersonEmail = TFFsyncrec[0].TouristEmailAddress;
                                                                   updateTac.Person_Email_External__c = TFFsyncrec[0].TouristEmailAddress;
                                                                   updateTac.PersonBirthdate = (TFFsyncrec[0].TouristDateOfBirth!=null?date.valueof(TFFsyncrec[0].TouristDateOfBirth):null);
                                                                   updateTac.PersonMobilePhone = TFFsyncrec[0].TouristPhoneNumber;
                                                                   updateTac.PersonMailingPostalCode = TFFsyncrec[0].TouristPostalCode;
                                                                   updateTac.Owning_Country__c = TFFsyncrec[0].CountryOfPurchase ;
                                                                   updateTac.RecordTypeId = Recordtypeid;
                                                                   updateTac.Passport_Number__c = TFFsyncrec[0].TouristPassportNumber ;
                                                                   updateTac.Premier_Pass_ID__c = TFFsyncrec[0].TouristPremierPassId ;
                                                                   updateTac.External_Passport_Number__c = TFFsyncrec[0].TouristPassportNumber ;
                                                                   updateTac.External_Premier_Pass_ID__c = TFFsyncrec[0].TouristPremierPassId ; 
                                                                   update updateTac;
                                                               }
                    
                    
                    tff.Name = TFFsyncrec[0].TaxFreeFormId;
                    tff.ExternalId_Tax_Free_Form_Id__c = TFFsyncrec[0].TaxFreeFormId;
                    tff.Latest_Payment_Status__c = TFFsyncrec[0].LatestPaymentStatus;
                    tff.Retailer_Id__c = TFFsyncrec[0].RetailerId;
                    if(accountmap.containsKey(TFFsyncrec[0].RetailerId))tff.Account_Shop__c = accountmap.get(TFFsyncrec[0].RetailerId).id;
                    else tff.Account_Shop__c = Label.DefaultRetailerAccount;
                    tff.Vendor_Number__c = TFFsyncrec[0].VendorNumber ;
                    tff.Country_Of_Purchase__c = TFFsyncrec[0].CountryOfPurchase ;
                    tff.Sales_Amount__c = (TFFsyncrec[0].SalesAmount!=null?decimal.valueof(TFFsyncrec[0].SalesAmount):0);
                    tff.Sales_Currency__c = TFFsyncrec[0].SalesCurrency;
                    tff.Refund_Amount__c = (TFFsyncrec[0].RefundAmount!=null?decimal.valueof(TFFsyncrec[0].RefundAmount):0);
                    tff.Refund_Currency__c = TFFsyncrec[0].RefundCurrency;
                    
                    tff.P2_Entry_Date__c = (TFFsyncrec[0].P2EntryDate!=null?date.valueOf(TFFsyncrec[0].P2EntryDate):Null);
                    tff.Qualified_Date__c = (TFFsyncrec[0].QualifiedDate!=null?date.valueOf(TFFsyncrec[0].QualifiedDate):Null);
                    tff.Purchase_Date__c = (TFFsyncrec[0].PurchaseDate!=null?date.valueOf(TFFsyncrec[0].PurchaseDate):Null);
                    tff.Customs_Date_Stamp__c = (TFFsyncrec[0].CustomsDateStamp!=null?date.valueOf(TFFsyncrec[0].CustomsDateStamp):Null);
                    tff.Refund_Date__c = (TFFsyncrec[0].RefundDate!=null?date.valueOf(TFFsyncrec[0].RefundDate):Null);
                    tff.Refund_Method__c = TFFsyncrec[0].RefundMethod;
                    tff.Cheque_Number__c = TFFsyncrec[0].ChequeNumber;
                    tff.Masked_Card_Number__c = TFFsyncrec[0].MaskedCardNumber;
                    tff.Credit_Card_Number__c = TFFsyncrec[0].MaskedCardNumber;
                    tff.Alipay_Id__c = TFFsyncrec[0].AlipayId;
                    tff.Bank_Account_Number__c = TFFsyncrec[0].BankAccountNumber;
                    tff.Exit_Point__c = (TFFsyncrec[0].ExitPoint!=null?integer.valueof(TFFsyncrec[0].ExitPoint):NULL);
                    tff.Priority__c = TFFsyncrec[0].Priority;
                    tff.Tourist_Premier_Pass_Id__c = TFFsyncrec[0].TouristPremierPassId;
                    tff.Tourist_Passport_Number__c = TFFsyncrec[0].TouristPassportNumber;
                    tff.Tourist_Passport_Issuing_Country__c =  TFFsyncrec[0].TouristPassportIssuingCountry;
                    tff.Tourist_Email_Address__c = TFFsyncrec[0].TouristEmailAddress;
                    tff.Tourist_Final_Destination__c = TFFsyncrec[0].TouristFinalDestination;
                    tff.Last_Sync__c = system.now();
                    if(tffrecord.Tourist__c!=null) 
                        tff.Tourist__c = tffrecord.Tourist__c;
                    else  tff.Tourist__c = insertTac.id;
                    
                    
                    database.upsert(tff,ExtID_Field,false);}
                catch(exception ex){
                    system.debug('Exception happened while updating  data in salesforce: ' + ex);
                    Debug_Log_Track__c dl = new Debug_Log_Track__c();
                    dl.Apex_class_name__c = 'Tax_Free_Form_Search_Ctrl';
                    dl.LineNumber__c = ex.getLineNumber();
                    dl.Message__c = ex.getMessage();
                    dl.StackTrace__c = ex.getStackTraceString();
                    dl.Type__c = ex.getTypeName();
                    insert dl;
                    
                }
                
            }
            
        }
        PageReference TffPage = new ApexPages.StandardController(tff).view();
        TffPage.setRedirect(true);
        return TffPage;
    }
    Public void insertDataInSf(){
        Schema.SObjectField ExtID_Field = Tax_Free_Form__c.Fields.ExternalId_Tax_Free_Form_Id__c;
        Schema.SObjectField ExtEmail_Field = account.Fields.Person_Email_External__c;
        Schema.SObjectField ExtPassport_Field = account.Fields.External_Passport_Number__c;
        Schema.SObjectField ExtPremier_Pass_Field = account.Fields.External_Premier_Pass_ID__c;
        string Recordtypeid = [select Id from RecordType where (Name='Tourist') and (SobjectType='Account')].id;
        list<Tax_Free_Form__c> upsertTFFlist = new list<Tax_Free_Form__c>();
        Map<string ,account> TaccinsertEmail_map = new Map<string ,account>();
        Map<string ,account> TaccinsertPassport_map = new Map<string ,account>();
        Map<string ,account> Taccinsertpremierpass_map = new Map<string ,account>();
        Map<string ,account> Taccinsertname_map = new Map<string ,account>();
        map<String,account> Taccmap = new map<String,account>();
        map<string,account> accountmap = new map<string,account>();
        set<string> setRetailerIds = new set<string>();
        for(string tfid:selectedTFFids.split(',')){
            for(TFFFintraxObj tfobj:FinRecordlist){
                if(tfobj.RetailerId != null)setRetailerIds.add(tfobj.RetailerId);
            }
        }
        for(account a:[select id,Account_ID__c,PersonEmail from account where Account_ID__c IN: setRetailerIds Or PersonEmail!=null]){
            if(a.Account_ID__c!=null) accountmap.put(a.Account_ID__c,a);
            if(a.PersonEmail != null) Taccmap.put(a.PersonEmail,a);
        }
        
        system.debug('---Taccmap--'+Taccmap);
        for(string tfid:selectedTFFids.split(',')){
            for(TFFFintraxObj tfobj:FinRecordlist){
                if(tfid==tfobj.TaxFreeFormId){
                    // if(!Taccmap.containsKey(tfobj.TouristEmailAddress)){
                    if((String.isNotBlank(tfobj.TouristFirstName))||
                       (String.isNotBlank(tfobj.TouristLastName) )){
                           account Tac = new account();
                           Tac.firstname =  tfobj.TouristFirstName;
                           //Tac.lastname = 'last';
                           Tac.lastname =  ((tfobj.TouristLastName!=''&&tfobj.TouristLastName!=null)?tfobj.TouristLastName:tfobj.TouristFirstName);
                           Tac.PersonMailingStreet = tfobj.TouristAddress;
                           tac.PersonEmail = tfobj.TouristEmailAddress;
                           Tac.Person_Email_External__c = tfobj.TouristEmailAddress;
                           tac.PersonBirthdate = (tfobj.TouristDateOfBirth!=null?date.valueof(tfobj.TouristDateOfBirth):null);
                           tac.PersonMobilePhone = tfobj.TouristPhoneNumber;
                           tac.PersonMailingPostalCode = tfobj.TouristPostalCode;
                           tac.Owning_Country__c = tfobj.CountryOfPurchase ;
                           tac.Passport_Number__c = tfobj.TouristPassportNumber ;
                           tac.Premier_Pass_ID__c = tfobj.TouristPremierPassId ;
                           tac.External_Passport_Number__c = tfobj.TouristPassportNumber ;
                           tac.External_Premier_Pass_ID__c = tfobj.TouristPremierPassId ;
                           tac.RecordTypeId = Recordtypeid;
                           system.debug('----tacc---'+tac);
                           if(tac.PersonEmail!=null&&tac.PersonEmail!= '')
                               TaccinsertEmail_map.put(tac.PersonEmail,tac);
                           else if(tac.Passport_Number__c!=null&&tac.Passport_Number__c!='')
                               TaccinsertPassport_map.put(tac.Passport_Number__c,tac);
                           else if( tac.Premier_Pass_ID__c!=null &&  tac.Premier_Pass_ID__c!='') 
                               Taccinsertpremierpass_map.put(tac.Premier_Pass_ID__c,tac);
                           else if(tac.LastName !=null && tac.LastName!='' )
                               Taccinsertname_map.put(tac.LastName+tac.FirstName,tac);
                       }
                    
                    
                    Tax_Free_Form__c TFF = new Tax_Free_Form__c();
                    tff.Name = tfobj.TaxFreeFormId;
                    tff.ExternalId_Tax_Free_Form_Id__c = tfobj.TaxFreeFormId;
                    tff.Latest_Payment_Status__c = tfobj.LatestPaymentStatus;
                    tff.Retailer_Id__c = tfobj.RetailerId;
                    if(accountmap.containsKey(tfobj.RetailerId))tff.Account_Shop__c = accountmap.get(tfobj.RetailerId).id;
                    else tff.Account_Shop__c = Label.DefaultRetailerAccount;
                    tff.Vendor_Number__c = tfobj.VendorNumber ;
                    tff.Country_Of_Purchase__c = tfobj.CountryOfPurchase ;
                    tff.Sales_Amount__c = (tfobj.SalesAmount!=null?decimal.valueof(tfobj.SalesAmount):0);
                    tff.Sales_Currency__c = tfobj.SalesCurrency;
                    tff.Refund_Amount__c = (tfobj.RefundAmount!=null?decimal.valueof(tfobj.RefundAmount):0);
                    tff.Refund_Currency__c = tfobj.RefundCurrency;
                    
                    tff.P2_Entry_Date__c = (tfobj.P2EntryDate!=null?date.valueOf(tfobj.P2EntryDate):Null);
                    tff.Qualified_Date__c = (tfobj.QualifiedDate!=null?date.valueOf(tfobj.QualifiedDate):Null);
                    tff.Purchase_Date__c = (tfobj.PurchaseDate!=null?date.valueOf(tfobj.PurchaseDate):Null);
                    tff.Customs_Date_Stamp__c = (tfobj.CustomsDateStamp!=null?date.valueOf(tfobj.CustomsDateStamp):Null);
                    tff.Refund_Date__c = (tfobj.RefundDate!=null?date.valueOf(tfobj.RefundDate):Null);
                    tff.Refund_Method__c = tfobj.RefundMethod;
                    tff.Cheque_Number__c = tfobj.ChequeNumber;
                    tff.Masked_Card_Number__c = tfobj.MaskedCardNumber;
                    tff.Credit_Card_Number__c = tfobj.MaskedCardNumber;
                    tff.Alipay_Id__c = tfobj.AlipayId;
                    tff.Bank_Account_Number__c = tfobj.BankAccountNumber;
                    tff.Exit_Point__c = (tfobj.ExitPoint!=null?integer.valueof(tfobj.ExitPoint):NULL);
                    tff.Priority__c = tfobj.Priority;
                    tff.Tourist_First_Name__c = tfobj.TouristFirstName;
                    tff.Tourist_Last_Name__c = ((tfobj.TouristLastName!=''&&tfobj.TouristLastName!=null)?tfobj.TouristLastName:tfobj.TouristFirstName);
                    tff.Tourist_Premier_Pass_Id__c = tfobj.TouristPremierPassId;
                    tff.Tourist_Passport_Number__c = tfobj.TouristPassportNumber;
                    tff.Tourist_Passport_Issuing_Country__c =  tfobj.TouristPassportIssuingCountry;
                    tff.Tourist_Email_Address__c = tfobj.TouristEmailAddress;
                    tff.Tourist_Final_Destination__c = tfobj.TouristFinalDestination;
                    tff.Last_Sync__c = system.now();
                    upsertTFFlist.add(tff);
                    
                    
                }
            }
            
        }
        system.debug('---TaccinsertEmail_map--'+TaccinsertEmail_map);
        system.debug('---TaccinsertPassport_map--'+TaccinsertPassport_map);
        system.debug('---Taccinsertpremierpass_map--'+Taccinsertpremierpass_map);
        system.debug('---Taccinsertname_map'+Taccinsertname_map);
        try{
            if(!TaccinsertEmail_map.isEmpty()){
                system.debug('---TaccinsertEmail_map.isEmpty()--'+TaccinsertEmail_map.isEmpty());
                database.upsert(TaccinsertEmail_map.values(),ExtEmail_Field,false);
            }
            
            else if(!TaccinsertPassport_map.isEmpty()){
                system.debug('---TaccinsertPassport_map.isEmpty()--'+TaccinsertPassport_map.isEmpty());
                database.upsert(TaccinsertPassport_map.values(),ExtPassport_Field,false);
            }
            
            else if(!Taccinsertpremierpass_map.isEmpty()){
                system.debug('---Taccinsertpremierpass_map.isEmpty()--'+Taccinsertpremierpass_map.isEmpty());
                database.upsert(Taccinsertpremierpass_map.values(),ExtPremier_Pass_Field,false);
            }
            else if(!Taccinsertname_map.isEmpty()){
                system.debug('---Taccinsertname_map.isEmpty()--'+Taccinsertname_map.isEmpty());
                database.insert(Taccinsertname_map.values(),false);
            }
            
            for(Tax_Free_Form__c tf :upsertTFFlist){
                if(tf.Tourist_Email_Address__c!=null&&tf.Tourist_Email_Address__c!=''&&TaccinsertEmail_map.containsKey(tf.Tourist_Email_Address__c))
                    tf.Tourist__c = TaccinsertEmail_map.get(tf.Tourist_Email_Address__c).id;
                else if(tf.Tourist_Passport_Number__c!=null&&tf.Tourist_Passport_Number__c!=''&&TaccinsertPassport_map.containsKey(tf.Tourist_Passport_Number__c))
                    tf.Tourist__c = TaccinsertPassport_map.get(tf.Tourist_Passport_Number__c).id;
                else if(tf.Tourist_Premier_Pass_Id__c!=null&&tf.Tourist_Premier_Pass_Id__c!=''&&Taccinsertpremierpass_map.containsKey(tf.Tourist_Premier_Pass_Id__c))
                    tf.Tourist__c = Taccinsertpremierpass_map.get(tf.Tourist_Premier_Pass_Id__c).id;
                else if(tf.Tourist_Last_Name__c !=null && tf.Tourist_Last_Name__c!='' && Taccinsertname_map.containsKey(tf.Tourist_Last_Name__c+tf.Tourist_First_Name__c)){
                    //system.debug('enter in name');
                    tf.Tourist__c = Taccinsertname_map.get(tf.Tourist_Last_Name__c+tf.Tourist_First_Name__c).id;
                }
            }
            system.debug('upsertTFFlist'+upsertTFFlist);
            database.upsert(upsertTFFlist,ExtID_Field,false);
            sfSearch();   
            
        }
        Catch(exception ex){
            system.debug('Exception happened while inserting data in salesforce: ' + ex);
            Debug_Log_Track__c dl = new Debug_Log_Track__c();
            dl.Apex_class_name__c = 'Tax_Free_Form_Search_Ctrl';
            dl.LineNumber__c = ex.getLineNumber();
            dl.Message__c = ex.getMessage();
            dl.StackTrace__c = ex.getStackTraceString();
            dl.Type__c = ex.getTypeName();
            insert dl;
        }
        
    }
    
    
}