unpackaged/main/default/objects/Account/fields/Account_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Phone_Number__c</fullName>
    <description>This field can be used for Standard Phone Number field displays normal number formal not splitted to strings.</description>
    <formula>SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(Phone, &#39;.&#39;, &#39;&#39;) , &#39; &#39;, &#39;&#39;) , &#39;-&#39;, &#39;&#39;) , &#39;)&#39;, &#39;&#39;) , &#39;(&#39;, &#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Phone Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AllCallsInfo__c/AllCallsInfo__c.object-meta.xml
<CustomObject>
    <label>All Calls Info</label>
    <nameField>
        <displayFormat>CAL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Calls Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/AllCallsInfo__c/fields/Call_From__c.field-meta.xml
<CustomField>
    <fullName>Call_From__c</fullName>
    <label>Call From</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AllCallsInfo__c/fields/Call_To__c.field-meta.xml
<CustomField>
    <fullName>Call_To__c</fullName>
    <label>Call To</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/AllCallsInfo__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incoming</fullName>
            </value>
            <value>
                <fullName>Outgoing</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Notified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AllCallsInfo__c/fields/User_Agent__c.field-meta.xml
<CustomField>
    <fullName>User_Agent__c</fullName>
    <label>SF User</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Contact_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Contact_Mobile__c</fullName>
    <description>This field can be used for Standard Mobile  field displays normal number formal not splitted to strings.</description>
    <formula>SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( SUBSTITUTE(MobilePhone, &#39;.&#39;, &#39;&#39;) , &#39; &#39;, &#39;&#39;) , &#39;-&#39;, &#39;&#39;) , &#39;)&#39;, &#39;&#39;) , &#39;(&#39;, &#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Mobile</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <description>This field can be used for combination of Call image and Contact Mobile</description>
    <formula>Call__c + Contact_Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/StreamingObject__c/StreamingObject__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Incoming Call</label>
</CustomObject>

unpackaged/main/default/objects/StreamingObject__c/fields/Call_To__c.field-meta.xml
<CustomField>
    <fullName>Call_To__c</fullName>
    <description>call to</description>
    <label>Call To</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/StreamingObject__c/fields/Calling_From__c.field-meta.xml
<CustomField>
    <fullName>Calling_From__c</fullName>
    <label>Calling From</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/StreamingObject__c/fields/Lync_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Lync_Notifications__c</fullName>
    <label>Lync Notifications</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/LyncId__c.field-meta.xml
<CustomField>
    <fullName>LyncId__c</fullName>
    <label>LyncId</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/MttlOutgoingCallStdcontroller.cls
public with sharing class MttlOutgoingCallStdcontroller{ 
 Public list<user> lstusr{get;set;}
 //Public list<order> lstordr{get;set;}
 Public boolean globalsearchblock{get;set;}
 Public boolean mainformblock{get;set;}
 //public boolean contactblock {get;set;}
 public String incomingcallerId{set;get;}
 public String popupcontactName{get;set;}
 Public list < contact > lstcon {get;set;}
 //Public boolean accountblock{get;set;}
 public List < Account > accountList {get;set;}
 public StreamingObject__c callingInformation {get;set;}
 Public string getConMobile;
 public MttlOutgoingCallStdcontroller() {
      String getConMobileno=Apexpages.currentpage().getparameters().get('outgoingId');
      system.debug('@@@@@getConMobileno@@@@'+getConMobile);
      getConMobile='+'+getConMobileno.trim();
      system.debug('@@@@@'+getConMobile);
      lstusr=[Select Name,LyncId__c FROM User];
      
      callingInformation = [Select Id, createdbyId,Name,Calling_From__c,SetupOwner.name,SetupOwnerid FROM StreamingObject__c where SetupOwnerid=:userinfo.getUserId()];
  
      accountList = [Select id, Name, Phone, Account_Phone_Number__c, (Select Name, Email, MobilePhone, title, Phone, AccountId, Account.Name, Mobile__c, Contact_Mobile__c From Contacts) From Account where Account_Phone_Number__c=:getConMobile];
      mainformblock=true;
      globalsearchblock=false;
      if (accountList.size() == 0) {        
           try{
               lstcon = [Select Id,Name, Email, MobilePhone, title, Phone, AccountId, Account.Name, Mobile__c,(SELECT id,casenumber, subject, priority, description FROM cases) Contact_Mobile__c From Contact where Mobile__c LIKE:getConMobile];
               popupcontactName=lstcon[0].Name;incomingcallerId=lstcon[0].Id;
           }
           Catch(Exception e){
               popupcontactName=callingInformation.Calling_From__c;
               mainformblock=false;
               globalsearchblock=true;
               
           }
      }    
}

 
 // SOSL for searching account,contacts and Cases
    
    public list<list<sObject>> soslResults {
        get {
            if(getConMobile != null && getConMobile != '') {
                soslResults = [FIND :getConMobile IN ALL FIELDS RETURNING  Contact(name,Contact_Mobile__c),Account(name,phone)];
            }
            return soslResults;
        }
        set;
    }
    
    public class searchResultRow{
        public string sObjectTypeName {get;set;}
        public sObject record {get;set;}
        
        public searchResultRow(sObject pObject) {
            record = pObject;
            sObjectTypeName = pObject.getSObjectType().getDescribe().getLabel();
        }
    }   
    
    public list<searchResultRow> searchResults {
        
        get {
            searchResults = new list<searchResultRow>();
            if(soslResults != null) {
             
                //Loop through the list of list of sObjects from our sosl query
                for(list<sObject> objectList : soslResults) {
                    for(sObject obj : objectList) {
                        searchResults.add(new searchResultRow(obj));
                    }
                }
            }
            else if(soslResults == null){ 
            }
            return searchResults;
        }
        set;
    }
    

 public void lyncInboundCall(String userName,String calfrom,String callstatus) {
    
      
      StreamingObject__c topic = new StreamingObject__c();
      topic.Name = userName;
      topic.Calling_From__c = calfrom;
      topic.Lync_Notifications__c =callstatus;
      insert topic;
 }
 
 
 public void CreateOutgoingRecord(){
        AllCallsInfo__c alCalInfo=new AllCallsInfo__c(); 
        alCalInfo.Call_From__c=[Select LyncId__c From User where id=:UserInfo.getUserId()].LyncId__c;
        alCalInfo.Call_Type__c=String.valueOf(MttlLyncEnums.LyncCallTypes.Outgoing);
        alCalInfo.User_Agent__c=[Select Name,LyncId__c From User where id=:UserInfo.getUserId()].Name;
        alCalInfo.Call_To__c=getConMobile;
        //insert alCalInfo;
 
 }
 
 
}