unpackaged/main/default/objects/Account/fields/Company_Sector__c.field-meta.xml
<CustomField>
    <fullName>Company_Sector__c</fullName>
    <label>Company Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial Partner</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Owning_Country__c.field-meta.xml
<CustomField>
    <fullName>Owning_Country__c</fullName>
    <defaultValue>IF($User.Country = &quot;United Kingdom&quot;, &quot;United Kingdom&quot;,
IF($User.Country = &quot;Austria&quot;, &quot;Austria&quot;,
IF($User.Country = &quot;Belgium&quot;, &quot;Belgium&quot;,
IF($User.Country = &quot;Colombia&quot;, &quot;Colombia&quot;,
IF($User.Country = &quot;Czech Republic&quot;, &quot;Czech Republic&quot;,
IF($User.Country = &quot;Denmark&quot;, &quot;Denmark&quot;,
IF($User.Country = &quot;Finland&quot;, &quot;Finland&quot;,
IF($User.Country = &quot;France&quot;, &quot;France&quot;,
IF($User.Country = &quot;Germany&quot;, &quot;Germany&quot;,
IF($User.Country = &quot;Greece&quot;, &quot;Greece&quot;,
IF($User.Country = &quot;Hong Kong&quot;, &quot;Hong Kong&quot;,
IF($User.Country = &quot;Hungary&quot;, &quot;Hungary&quot;,
IF($User.Country = &quot;Iceland&quot;, &quot;Iceland&quot;,
IF($User.Country = &quot;Ireland&quot;, &quot;Ireland&quot;,
IF($User.Country = &quot;Italy&quot;, &quot;Italy&quot;,
IF($User.Country = &quot;Korea, Republic of&quot;, &quot;Korea, Republic of&quot;,
IF($User.Country = &quot;Poland&quot;, &quot;Poland&quot;,
IF($User.Country = &quot;Portugal&quot;, &quot;Portugal&quot;,
IF($User.Country = &quot;Singapore&quot;, &quot;Singapore&quot;,
IF($User.Country = &quot;Spain&quot;, &quot;Spain&quot;,
IF($User.Country = &quot;Sweden&quot;, &quot;Sweden&quot;,
IF($User.Country = &quot;United States&quot;, &quot;United States&quot;,
IF($User.Country = &quot;Canada&quot;, &quot;Canada&quot;,
IF($User.Country = &quot;Turkey&quot;, &quot;Turkey&quot;,
IF($User.Country = &quot;Switzerland&quot;, &quot;&quot;, null)))))))))))))))))))))))))</defaultValue>
    <label>Owning Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company_Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Tax_Free_Form__c/Tax_Free_Form__c.object-meta.xml
<CustomObject>
    <label>Tax Free Form</label>
    <nameField>
        <label>Tax Free Form Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Free Form</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/New_Tourist_Form_Ctrl_Test.cls
@isTest
public class New_Tourist_Form_Ctrl_Test {
    static testMethod void New_Tourist_Form_Ctrl_Test_Mtd(){
        Test.startTest();
        
        Id touristRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Tourist').getRecordTypeId();
        Account acc = new Account();
        acc.FirstName = 'Test Record';
        acc.LastName = 'Test Record';
        acc.RecordTypeId = touristRecordTypeId;
        acc.Owning_Country__c = 'Poland';
        acc.Company_Sector__c = 'Retail';
        insert acc; 
        
        Tax_Free_Form__c tff = new Tax_Free_Form__c();
        tff.Name = '132464178521';
        insert tff;

        Test.setCurrentPageReference(new PageReference('Page.New_Tourist_Form')); 
        System.currentPageReference().getParameters().put('ttfId', tff.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(tff);
        New_Tourist_Form_Ctrl ntf = new New_Tourist_Form_Ctrl(sc);
        ntf.saveAcc();
        ntf.cancelAcc();
        
        Test.stopTest();
    }
}