unpackaged/main/default/objects/Account/fields/Company_Sector__c.field-meta.xml
<CustomField>
    <fullName>Company_Sector__c</fullName>
    <label>Company Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial Partner</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Owning_Country__c.field-meta.xml
<CustomField>
    <fullName>Owning_Country__c</fullName>
    <defaultValue>IF($User.Country = &quot;United Kingdom&quot;, &quot;United Kingdom&quot;,
IF($User.Country = &quot;Austria&quot;, &quot;Austria&quot;,
IF($User.Country = &quot;Belgium&quot;, &quot;Belgium&quot;,
IF($User.Country = &quot;Colombia&quot;, &quot;Colombia&quot;,
IF($User.Country = &quot;Czech Republic&quot;, &quot;Czech Republic&quot;,
IF($User.Country = &quot;Denmark&quot;, &quot;Denmark&quot;,
IF($User.Country = &quot;Finland&quot;, &quot;Finland&quot;,
IF($User.Country = &quot;France&quot;, &quot;France&quot;,
IF($User.Country = &quot;Germany&quot;, &quot;Germany&quot;,
IF($User.Country = &quot;Greece&quot;, &quot;Greece&quot;,
IF($User.Country = &quot;Hong Kong&quot;, &quot;Hong Kong&quot;,
IF($User.Country = &quot;Hungary&quot;, &quot;Hungary&quot;,
IF($User.Country = &quot;Iceland&quot;, &quot;Iceland&quot;,
IF($User.Country = &quot;Ireland&quot;, &quot;Ireland&quot;,
IF($User.Country = &quot;Italy&quot;, &quot;Italy&quot;,
IF($User.Country = &quot;Korea, Republic of&quot;, &quot;Korea, Republic of&quot;,
IF($User.Country = &quot;Poland&quot;, &quot;Poland&quot;,
IF($User.Country = &quot;Portugal&quot;, &quot;Portugal&quot;,
IF($User.Country = &quot;Singapore&quot;, &quot;Singapore&quot;,
IF($User.Country = &quot;Spain&quot;, &quot;Spain&quot;,
IF($User.Country = &quot;Sweden&quot;, &quot;Sweden&quot;,
IF($User.Country = &quot;United States&quot;, &quot;United States&quot;,
IF($User.Country = &quot;Canada&quot;, &quot;Canada&quot;,
IF($User.Country = &quot;Turkey&quot;, &quot;Turkey&quot;,
IF($User.Country = &quot;Switzerland&quot;, &quot;&quot;, null)))))))))))))))))))))))))</defaultValue>
    <label>Owning Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company_Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Add_On__c/Add_On__c.object-meta.xml
<CustomObject>
    <label>Add On</label>
    <nameField>
        <displayFormat>AO-{0000}</displayFormat>
        <label>Add On Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Add On</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Add_On__c/fields/Click_Collect_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Click_Collect_Total_Price__c</fullName>
    <label>Click &amp; Collect Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/Digital_Commerce_Option_Price__c.field-meta.xml
<CustomField>
    <fullName>Digital_Commerce_Option_Price__c</fullName>
    <label>Digital Commerce Option Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/Distance_Selling_Checkout__c.field-meta.xml
<CustomField>
    <fullName>Distance_Selling_Checkout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Distance Selling Checkout</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/OMS_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>OMS_Total_Price__c</fullName>
    <label>OMS Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/Per_DC_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Per_DC_Implementation__c</fullName>
    <label>Per DC Implementation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/Per_Independently_Managed_Brand__c.field-meta.xml
<CustomField>
    <fullName>Per_Independently_Managed_Brand__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Per Independently Managed Brand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/Per_Website__c.field-meta.xml
<CustomField>
    <fullName>Per_Website__c</fullName>
    <label>Per Website</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/Smart_POS_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Smart_POS_Total_Price__c</fullName>
    <label>Smart POS Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/SPOS_Price__c.field-meta.xml
<CustomField>
    <fullName>SPOS_Price__c</fullName>
    <label>SPOS Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/Subscription_Fees__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Fees__c</fullName>
    <label>Subscription Fees</label>
    <referenceTo>Subscription_Fees__c</referenceTo>
    <relationshipLabel>Add On</relationshipLabel>
    <relationshipName>Add_On</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Add_On__c/fields/Webfront__c.field-meta.xml
<CustomField>
    <fullName>Webfront__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Webfront</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company_Sector__c.field-meta.xml
<CustomField>
    <fullName>Company_Sector__c</fullName>
    <description>Account Company Sector - requested by Finance on 24/1/22</description>
    <formula>TEXT(Account.Company_Sector__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Sector</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/Subscription_Fees__c.object-meta.xml
<CustomObject>
    <description>For New Proximis Products - Saurabh 29/03/2022</description>
    <label>Subscription Fees</label>
    <nameField>
        <displayFormat>SF-{0000}</displayFormat>
        <label>Subscription Fees Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Click_Collect__c.field-meta.xml
<CustomField>
    <fullName>Click_Collect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Click &amp; Collect</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Digital_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Digital_Commerce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Digital Commerce</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Number_Of_Associates__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Associates__c</fullName>
    <label>Number Of Associates</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/OMS__c.field-meta.xml
<CustomField>
    <fullName>OMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OMS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Subscription Fees</relationshipLabel>
    <relationshipName>Yearly_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Predicted_GMV__c.field-meta.xml
<CustomField>
    <fullName>Predicted_GMV__c</fullName>
    <label>User - Predicted GMV Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Predicted_GMV_Price__c.field-meta.xml
<CustomField>
    <fullName>Predicted_GMV_Price__c</fullName>
    <label>Predicted GMV Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Predicted_GMV_Value__c.field-meta.xml
<CustomField>
    <fullName>Predicted_GMV_Value__c</fullName>
    <label>Predicted GMV Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Smart_POS__c.field-meta.xml
<CustomField>
    <fullName>Smart_POS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Smart POS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Subscription_Fees__c/fields/Support_Level_Price__c.field-meta.xml
<CustomField>
    <fullName>Support_Level_Price__c</fullName>
    <label>Support Level Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/x_SubscriptionFeesLookupTest.cls
@IsTest
public class x_SubscriptionFeesLookupTest {
	static void setup() {
  	}
    
    @IsTest
  	static void setClickAndCollect() {

          //insert test account
          Account acc = new Account(name='Test');
          acc.Owning_Country__c = 'United Kingdom';
          acc.Company_Sector__c = 'Retail';
          insert acc;
          
          //insert test opportunity
          Opportunity opp = new Opportunity(name='Test');
          opp.AccountId = acc.Id;
          opp.StageName = 'Opportunity Recorded';
          opp.CloseDate = Date.newInstance(2030, 12, 12);
          insert opp;
    
          //insert test Subscription_Fees__c
          Subscription_Fees__c sFee = new Subscription_Fees__c();
          sFee.Click_Collect__c = TRUE;
          sFee.Opportunity__c = opp.Id;
          insert sFee;
              
          //insert test Add_On__c
          Add_On__c addOn = new Add_On__c();
          addOn.Subscription_Fees__c = sFee.Id;
          insert addOn;
    
          List<Id> lstSFeesIds = new List<Id>();
          lstSFeesIds.add(sFee.Id);
              
          Test.startTest();
              
          //call class
          x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
              
          //get Add_On__c record to check update
          Add_On__c addOnTest = [SELECT Id, Click_Collect_Total_Price__c  //other fields
                                    FROM Add_On__c 
                                    LIMIT 1];
    
          //check amount
          System.assertEquals(12000.00, addOnTest.Click_Collect_Total_Price__c);
    
          Test.stopTest();     

  	}

    @IsTest
  	static void setOMS() {

		//insert test account
      	Account acc = new Account(name='Test');
      	acc.Owning_Country__c = 'United Kingdom';
      	acc.Company_Sector__c = 'Retail';
       	insert acc;
        
		//insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;

		  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.OMS__c = TRUE;
      sFee.Opportunity__c = opp.Id;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      insert addOn;

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Add_On__c record to check update
      Add_On__c addOnTest = [SELECT Id, OMS_Total_Price__c  //other fields
                           		FROM Add_On__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(12000.00, addOnTest.OMS_Total_Price__c);

      Test.stopTest();     

  	}

    @IsTest
  	static void setSMARTPosWithinBand() {

		  //insert test account
      Account acc = new Account(name='Test');
      acc.Owning_Country__c = 'United Kingdom';
      acc.Company_Sector__c = 'Retail';
      insert acc;
        
		  //insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;

		  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.Smart_POS__c = TRUE;
      sFee.Opportunity__c = opp.Id;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      addOn.Number_Of_Associates__c = 30.00;
      insert addOn;

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Add_On__c record to check update
      Add_On__c addOnTest = [SELECT Id, Smart_POS_Total_Price__c  //other fields
                           		FROM Add_On__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(18000.00, addOnTest.Smart_POS_Total_Price__c);

      Test.stopTest();     

  	}

    @IsTest
  	static void setSMARTPosOutsideBand() {

		  //insert test account
      Account acc = new Account(name='Test');
      acc.Owning_Country__c = 'United Kingdom';
      acc.Company_Sector__c = 'Retail';
       insert acc;
        
		  //insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;

		  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.Smart_POS__c = TRUE;
      sFee.Opportunity__c = opp.Id;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      addOn.Number_Of_Associates__c = 850.00;
      addOn.SPOS_Price__c = 99999;
      insert addOn;

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Add_On__c record to check update
      Add_On__c addOnTest = [SELECT Id, Smart_POS_Total_Price__c  //other fields
                           		FROM Add_On__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(99999.00, addOnTest.Smart_POS_Total_Price__c);

      Test.stopTest();     

  	}
    
    @IsTest
  	static void setgmvWithinBand() {

		  //insert test account
      Account acc = new Account(name='Test');
      acc.Owning_Country__c = 'United Kingdom';
      acc.Company_Sector__c = 'Retail';
      insert acc;
        
		  //insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;

		  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.Opportunity__c = opp.Id;
      sFee.Predicted_GMV_Value__c = 500000;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      insert addOn;

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Subscription_Fees__c record to check update
      Subscription_Fees__c subFeesTest = [SELECT Id, Predicted_GMV_Price__c  //other fields
                           		FROM Subscription_Fees__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(3000.00, subFeesTest.Predicted_GMV_Price__c);

      Test.stopTest();     

  	}
    
    @IsTest
  	static void setgmvOutsideBand() {

		  //insert test account
      Account acc = new Account(name='Test');
    	acc.Owning_Country__c = 'United Kingdom';
      acc.Company_Sector__c = 'Retail';
      insert acc;
        
		  //insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;

		  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.Opportunity__c = opp.Id;
      sFee.Predicted_GMV_Value__c = 200000000;
      sfee.Predicted_GMV__c = 250000000;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      insert addOn;

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Subscription_Fees__c record to check update
      Subscription_Fees__c subFeesTest = [SELECT Id, Predicted_GMV_Price__c  //other fields
                           		FROM Subscription_Fees__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(250000000.00, subFeesTest.Predicted_GMV_Price__c);

      Test.stopTest();     

  	}
    
    @IsTest
  	static void setSupportBronze() {

		//insert test account
      Account acc = new Account(name='Test');
      acc.Owning_Country__c = 'United Kingdom';
      acc.Company_Sector__c = 'Retail';
      insert acc;
        
		  //insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;
        
	  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.Smart_POS__c = TRUE;
      sFee.Support_Level__c = 'Bronze';
      sFee.Opportunity__c = opp.Id;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      addOn.Number_Of_Associates__c = 30.00;
      insert addOn;        

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Subscription_Fees__c record to check update
      Subscription_Fees__c subFeeTest = [SELECT Id, Support_Level_Price__c //other fields
                           		FROM Subscription_Fees__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(0.00, subFeeTest.Support_Level_Price__c);

      Test.stopTest();     

  	}

    @IsTest
  	static void setSupportSilver() {
        
		  //insert test account
      Account acc = new Account(name='Test');
      acc.Owning_Country__c = 'United Kingdom';
      acc.Company_Sector__c = 'Retail';
      insert acc;
        
		  //insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;
        
		  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.Smart_POS__c = TRUE;
      sFee.Support_Level__c = 'Silver';
      sFee.Opportunity__c = opp.Id;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      addOn.Number_Of_Associates__c = 30.00;
      insert addOn;        

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Subscription_Fees__c record to check update
      Subscription_Fees__c subFeeTest = [SELECT Id, Support_Level_Price__c //other fields
                           		FROM Subscription_Fees__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(9540.00, subFeeTest.Support_Level_Price__c);

      Test.stopTest();     
        
    }    

    @IsTest
  	static void setSupportGold() {
        
		  //insert test account
      Account acc = new Account(name='Test');
      acc.Owning_Country__c = 'United Kingdom';
      acc.Company_Sector__c = 'Retail';
      insert acc;
        
		  //insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;
        
		  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.Smart_POS__c = TRUE;
      sFee.Support_Level__c = 'Gold';
      sFee.Opportunity__c = opp.Id;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      addOn.Number_Of_Associates__c = 30.00;
      insert addOn;        

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Subscription_Fees__c record to check update
      Subscription_Fees__c subFeeTest = [SELECT Id, Support_Level_Price__c //other fields
                           		FROM Subscription_Fees__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(19080.00, subFeeTest.Support_Level_Price__c);

      Test.stopTest();     
        
    }    
    
    @IsTest
  	static void setDigitalCommerce_DigitalCommerce() {

		  //insert test account
      Account acc = new Account(name='Test');
      acc.Owning_Country__c = 'United Kingdom';
      acc.Company_Sector__c = 'Retail';
      insert acc;
        
		  //insert test opportunity
      Opportunity opp = new Opportunity(name='Test');
      opp.AccountId = acc.Id;
      opp.StageName = 'Opportunity Recorded';
      opp.CloseDate = Date.newInstance(2030, 12, 12);
      insert opp;

		  //insert test Subscription_Fees__c
      Subscription_Fees__c sFee = new Subscription_Fees__c();
      sFee.Opportunity__c = opp.Id;
      sFee.Digital_Commerce__c = TRUE;
      insert sFee;
        
      //insert test Add_On__c
      Add_On__c addOn = new Add_On__c();
      addOn.Subscription_Fees__c = sFee.Id;
      addOn.Per_Independently_Managed_Brand__c = 3.00;
      insert addOn;

      List<Id> lstSFeesIds = new List<Id>();
      lstSFeesIds.add(sFee.Id);
        
      Test.startTest();
        
          //call class
      x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      //get Subscription_Fees__c record to check update
      Add_On__c addOnsTest = [SELECT Id, Digital_Commerce_Option_Price__c  //other fields
                           		FROM Add_On__c 
                           		LIMIT 1];

      //check amount
      System.assertEquals(26000.00, addOnsTest.Digital_Commerce_Option_Price__c);

      Test.stopTest();     

  	}  
    
    @IsTest
  	static void setDigitalCommerce_Webfront() {

		//insert test account
      	Account acc = new Account(name='Test');
      	acc.Owning_Country__c = 'United Kingdom';
      	acc.Company_Sector__c = 'Retail';
      	insert acc;
        
		//insert test opportunity
      	Opportunity opp = new Opportunity(name='Test');
      	opp.AccountId = acc.Id;
      	opp.StageName = 'Opportunity Recorded';
      	opp.CloseDate = Date.newInstance(2030, 12, 12);
      	insert opp;

		//insert test Subscription_Fees__c
      	Subscription_Fees__c sFee = new Subscription_Fees__c();
      	sFee.Opportunity__c = opp.Id;
      	sFee.Digital_Commerce__c = TRUE;
      	insert sFee;
        
      	//insert test Add_On__c
      	Add_On__c addOn = new Add_On__c();
      	addOn.Subscription_Fees__c = sFee.Id;
        addOn.Webfront__c = TRUE;
        addOn.Per_Independently_Managed_Brand__c = 3.00;
      	addOn.Per_DC_Implementation__c = 2.00;
      	addOn.Per_Website__c = 2.00;
      	insert addOn;

      	List<Id> lstSFeesIds = new List<Id>();
      	lstSFeesIds.add(sFee.Id);
        
      	Test.startTest();
        
        //call class
      	x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      	//get Subscription_Fees__c record to check update
      	Add_On__c addOnsTest = [SELECT Id, Digital_Commerce_Option_Price__c  //other fields
                           		FROM Add_On__c 
                           		LIMIT 1];

      	//check amount
      	System.assertEquals(42000.00, addOnsTest.Digital_Commerce_Option_Price__c);

      	Test.stopTest();     

  	}    

    @IsTest
  	static void setDigitalCommerce_DistanceSellingCheckout() {

		//insert test account
      	Account acc = new Account(name='Test');
      	acc.Owning_Country__c = 'United Kingdom';
      	acc.Company_Sector__c = 'Retail';
      	insert acc;
        
		//insert test opportunity
      	Opportunity opp = new Opportunity(name='Test');
      	opp.AccountId = acc.Id;
      	opp.StageName = 'Opportunity Recorded';
      	opp.CloseDate = Date.newInstance(2030, 12, 12);
      	insert opp;

		//insert test Subscription_Fees__c
      	Subscription_Fees__c sFee = new Subscription_Fees__c();
      	sFee.Opportunity__c = opp.Id;
      	sFee.Digital_Commerce__c = TRUE;
      	insert sFee;
        
      	//insert test Add_On__c
      	Add_On__c addOn = new Add_On__c();
      	addOn.Subscription_Fees__c = sFee.Id;
      	addOn.Per_Independently_Managed_Brand__c = 3.00;
        addOn.Distance_Selling_Checkout__c = TRUE;
      	addOn.Per_DC_Implementation__c = 2;
      	insert addOn;

      	List<Id> lstSFeesIds = new List<Id>();
      	lstSFeesIds.add(sFee.Id);
        
      	Test.startTest();
        
        //call class
      	x_SubscriptionFeesLookup.setTotals(lstSFeesIds);
        
      	//get Subscription_Fees__c record to check update
      	Add_On__c addOnsTest = [SELECT Id, Digital_Commerce_Option_Price__c  //other fields
                           		FROM Add_On__c 
                           		LIMIT 1];

      	//check amount
      	System.assertEquals(38000.00, addOnsTest.Digital_Commerce_Option_Price__c);

      	Test.stopTest();     

  	}    
        
}