unpackaged/main/default/objects/Account/fields/Company_Sector__c.field-meta.xml
<CustomField>
    <fullName>Company_Sector__c</fullName>
    <label>Company Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial Partner</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Owning_Country__c.field-meta.xml
<CustomField>
    <fullName>Owning_Country__c</fullName>
    <defaultValue>IF($User.Country = &quot;United Kingdom&quot;, &quot;United Kingdom&quot;,
IF($User.Country = &quot;Austria&quot;, &quot;Austria&quot;,
IF($User.Country = &quot;Belgium&quot;, &quot;Belgium&quot;,
IF($User.Country = &quot;Colombia&quot;, &quot;Colombia&quot;,
IF($User.Country = &quot;Czech Republic&quot;, &quot;Czech Republic&quot;,
IF($User.Country = &quot;Denmark&quot;, &quot;Denmark&quot;,
IF($User.Country = &quot;Finland&quot;, &quot;Finland&quot;,
IF($User.Country = &quot;France&quot;, &quot;France&quot;,
IF($User.Country = &quot;Germany&quot;, &quot;Germany&quot;,
IF($User.Country = &quot;Greece&quot;, &quot;Greece&quot;,
IF($User.Country = &quot;Hong Kong&quot;, &quot;Hong Kong&quot;,
IF($User.Country = &quot;Hungary&quot;, &quot;Hungary&quot;,
IF($User.Country = &quot;Iceland&quot;, &quot;Iceland&quot;,
IF($User.Country = &quot;Ireland&quot;, &quot;Ireland&quot;,
IF($User.Country = &quot;Italy&quot;, &quot;Italy&quot;,
IF($User.Country = &quot;Korea, Republic of&quot;, &quot;Korea, Republic of&quot;,
IF($User.Country = &quot;Poland&quot;, &quot;Poland&quot;,
IF($User.Country = &quot;Portugal&quot;, &quot;Portugal&quot;,
IF($User.Country = &quot;Singapore&quot;, &quot;Singapore&quot;,
IF($User.Country = &quot;Spain&quot;, &quot;Spain&quot;,
IF($User.Country = &quot;Sweden&quot;, &quot;Sweden&quot;,
IF($User.Country = &quot;United States&quot;, &quot;United States&quot;,
IF($User.Country = &quot;Canada&quot;, &quot;Canada&quot;,
IF($User.Country = &quot;Turkey&quot;, &quot;Turkey&quot;,
IF($User.Country = &quot;Switzerland&quot;, &quot;&quot;, null)))))))))))))))))))))))))</defaultValue>
    <label>Owning Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company_Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AMEX__c.field-meta.xml
<CustomField>
    <fullName>AMEX__c</fullName>
    <label>AMEX %</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company_Sector__c.field-meta.xml
<CustomField>
    <fullName>Company_Sector__c</fullName>
    <description>Account Company Sector - requested by Finance on 24/1/22</description>
    <formula>TEXT(Account.Company_Sector__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Sector</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/JCB__c.field-meta.xml
<CustomField>
    <fullName>JCB__c</fullName>
    <label>JCB %</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Payment_Card_Charge__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Charge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Card Charge</label>
    <referenceTo>Payment_Card_Charge__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/VISA_MC_Domestic_EEA__c.field-meta.xml
<CustomField>
    <fullName>VISA_MC_Domestic_EEA__c</fullName>
    <label>VISA/MC Domestic/EEA %</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/VISA_MC_Intl__c.field-meta.xml
<CustomField>
    <fullName>VISA_MC_Intl__c</fullName>
    <label>VISA/MC Intl %</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/Payment_Card_Charge__c.object-meta.xml
<CustomObject>
    <label>Payment Card Charge</label>
    <nameField>
        <displayFormat>PCC-{000000}</displayFormat>
        <label>Payment Card Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Card Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/Amex__c.field-meta.xml
<CustomField>
    <fullName>Amex__c</fullName>
    <label>Amex</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/Chinese_Wallets__c.field-meta.xml
<CustomField>
    <fullName>Chinese_Wallets__c</fullName>
    <label>Chinese Wallets</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/Chinese_Wallets_e_Comm__c.field-meta.xml
<CustomField>
    <fullName>Chinese_Wallets_e_Comm__c</fullName>
    <defaultValue>0.013</defaultValue>
    <label>Chinese Wallets e-Comm</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/JCB__c.field-meta.xml
<CustomField>
    <fullName>JCB__c</fullName>
    <label>JCB</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/Owning_Country__c.field-meta.xml
<CustomField>
    <fullName>Owning_Country__c</fullName>
    <label>Owning Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Owning_Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/UnionPay__c.field-meta.xml
<CustomField>
    <fullName>UnionPay__c</fullName>
    <label>UnionPay</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/Visa_MC_Domestic_EEA__c.field-meta.xml
<CustomField>
    <fullName>Visa_MC_Domestic_EEA__c</fullName>
    <label>Visa/MC Domestic/EEA</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/Visa_MC_Intl__c.field-meta.xml
<CustomField>
    <fullName>Visa_MC_Intl__c</fullName>
    <label>Visa/MC Intl.</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/globalValueSets/Owning_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Dominican Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Ecuador</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>El Salvador</fullName>
    </customValue>
    <customValue>
        <fullName>Equador</fullName>
    </customValue>
    <customValue>
        <fullName>Faroe Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>French West Indies</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <masterLabel>Owning Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/x_setOppPaymentCCTest.cls
@IsTest
public class x_setOppPaymentCCTest {
	static void setup() {
  	}
    
  	@IsTest
  	static void setPayCardChargeExists() {

		//insert test account
        Account acc = new Account(name='Test');
      	acc.Owning_Country__c = 'United Kingdom';
        acc.Company_Sector__c = 'Retail';
        insert acc;
        
		//insert test opportunity
        Opportunity opp = new Opportunity(name='Test');
        opp.AccountId = acc.Id;
        opp.StageName = 'Opportunity Recorded';
        opp.CloseDate = Date.newInstance(2030, 12, 12);
        insert opp;
        
		//insert test payment card charge
        Payment_Card_Charge__c pcc = new Payment_Card_Charge__c();
        pcc.Owning_Country__c = 'United Kingdom';
        pcc.Visa_MC_Intl__c = 1;
        pcc.Visa_MC_Domestic_EEA__c = 1;
        pcc.UnionPay__c = 1;
        pcc.JCB__c = 1;
        pcc.CurrencyIsoCode = 'GBP';
        pcc.Chinese_Wallets_e_Comm__c = 1;
        pcc.Chinese_Wallets__c = 1;
        pcc.Amex__c = 1;
        insert pcc;
        
        List<Id> lstOppIds = new List<Id>();
        lstOppIds.add(opp.Id);
        
        Test.startTest();
        
        String paymentCardChargeId = [SELECT Id, Owning_Country__c
                                      FROM Payment_Card_Charge__c
                                     ].Id;
        
        System.assert(paymentCardChargeId != null);  

        //call methis to set the opportunity payment card charge
        x_setOppPaymentCC.setPayCardCharge(lstOppIds);
        
        //get Opportunity record to check update
        Opportunity oppTest = [SELECT Id, Owning_Country__c, Payment_Card_Charge__c
                           		FROM Opportunity 
                           		LIMIT 1];
        
        //check the payment card charges match
        System.assertEquals(paymentCardChargeId, oppTest.Payment_Card_Charge__c);

        Test.stopTest();     
    
  }
    
  	@IsTest
  	static void setPayCardChargeMissing() {

		//insert test account
        Account acc = new Account(name='Test');
      	acc.Owning_Country__c = 'United Kingdom';
        acc.Company_Sector__c = 'Retail';
        insert acc;
        
		//insert test opportunity
        Opportunity opp = new Opportunity(name='Test');
        opp.AccountId = acc.Id;
        opp.StageName = 'Opportunity Recorded';
        opp.CloseDate = Date.newInstance(2030, 12, 12);
        insert opp;
        
		//insert test payment card charge
        Payment_Card_Charge__c pcc = new Payment_Card_Charge__c();
        pcc.Owning_Country__c = 'France';
        pcc.Visa_MC_Intl__c = 1;
        pcc.Visa_MC_Domestic_EEA__c = 1;
        pcc.UnionPay__c = 1;
        pcc.JCB__c = 1;
        pcc.CurrencyIsoCode = 'GBP';
        pcc.Chinese_Wallets_e_Comm__c = 1;
        pcc.Chinese_Wallets__c = 1;
        pcc.Amex__c = 1;
        insert pcc;
        
        List<Id> lstOppIds = new List<Id>();
        lstOppIds.add(opp.Id);
        
        Test.startTest();
        
        String paymentCardChargeId = [SELECT Id, Owning_Country__c
                                      FROM Payment_Card_Charge__c
                                     ].Id;
        
        System.assert(paymentCardChargeId != null);  

        //call methis to set the opportunity payment card charge
        x_setOppPaymentCC.setPayCardCharge(lstOppIds);
        
        //get Opportunity record to check update
        Opportunity oppTest = [SELECT Id, Owning_Country__c, Payment_Card_Charge__c
                           		FROM Opportunity 
                           		LIMIT 1];
        
        //check the payment card charges on Opp is null as there is no payment card charge existing
        System.assertEquals(null, oppTest.Payment_Card_Charge__c);

        Test.stopTest();     
    
  }
    
    
}