unpackaged/main/default/objects/Account/fields/Company_Sector__c.field-meta.xml
<CustomField>
    <fullName>Company_Sector__c</fullName>
    <label>Company Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial Partner</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Owning_Country__c.field-meta.xml
<CustomField>
    <fullName>Owning_Country__c</fullName>
    <defaultValue>IF($User.Country = &quot;United Kingdom&quot;, &quot;United Kingdom&quot;,
IF($User.Country = &quot;Austria&quot;, &quot;Austria&quot;,
IF($User.Country = &quot;Belgium&quot;, &quot;Belgium&quot;,
IF($User.Country = &quot;Colombia&quot;, &quot;Colombia&quot;,
IF($User.Country = &quot;Czech Republic&quot;, &quot;Czech Republic&quot;,
IF($User.Country = &quot;Denmark&quot;, &quot;Denmark&quot;,
IF($User.Country = &quot;Finland&quot;, &quot;Finland&quot;,
IF($User.Country = &quot;France&quot;, &quot;France&quot;,
IF($User.Country = &quot;Germany&quot;, &quot;Germany&quot;,
IF($User.Country = &quot;Greece&quot;, &quot;Greece&quot;,
IF($User.Country = &quot;Hong Kong&quot;, &quot;Hong Kong&quot;,
IF($User.Country = &quot;Hungary&quot;, &quot;Hungary&quot;,
IF($User.Country = &quot;Iceland&quot;, &quot;Iceland&quot;,
IF($User.Country = &quot;Ireland&quot;, &quot;Ireland&quot;,
IF($User.Country = &quot;Italy&quot;, &quot;Italy&quot;,
IF($User.Country = &quot;Korea, Republic of&quot;, &quot;Korea, Republic of&quot;,
IF($User.Country = &quot;Poland&quot;, &quot;Poland&quot;,
IF($User.Country = &quot;Portugal&quot;, &quot;Portugal&quot;,
IF($User.Country = &quot;Singapore&quot;, &quot;Singapore&quot;,
IF($User.Country = &quot;Spain&quot;, &quot;Spain&quot;,
IF($User.Country = &quot;Sweden&quot;, &quot;Sweden&quot;,
IF($User.Country = &quot;United States&quot;, &quot;United States&quot;,
IF($User.Country = &quot;Canada&quot;, &quot;Canada&quot;,
IF($User.Country = &quot;Turkey&quot;, &quot;Turkey&quot;,
IF($User.Country = &quot;Switzerland&quot;, &quot;&quot;, null)))))))))))))))))))))))))</defaultValue>
    <label>Owning Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company_Sector__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/Acquiring_Fees__c.object-meta.xml
<CustomObject>
    <label>Acquiring Fees</label>
    <nameField>
        <displayFormat>AF-{0000}</displayFormat>
        <label>Acquiring Fees Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acquiring Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Acquiring_Volume__c.field-meta.xml
<CustomField>
    <fullName>Acquiring_Volume__c</fullName>
    <inlineHelpText>Enter value in Millions i.e 1000000 should be entered as 1</inlineHelpText>
    <label>Acquiring Volume (Millions)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Actual_Fees__c.field-meta.xml
<CustomField>
    <fullName>Actual_Fees__c</fullName>
    <inlineHelpText>Enter actual Fees as a whole number i.e. for the bps value &#39;IC++: AF OF 25bps&#39;, enter 25, and for the value &#39;Blended: 1.60%&#39; enter 1.6</inlineHelpText>
    <label>Actual Fees</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <label>Minimum Fees</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Acquiring Fees</relationshipLabel>
    <relationshipName>Acquiring_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Setup__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POS/Online PBL</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Online PBL</fullName>
            </value>
            <value>
                <fullName>Online Cybersource</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <label>Scheme</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Platform__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa/Mastercard</fullName>
            </value>
            <value>
                <fullName>Union Pay</fullName>
            </value>
            <value>
                <fullName>Alipay</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>Alipay/WeChat</fullName>
                <isActive>false</isActive>
                <label>Alipay/WeChat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Setup__c.field-meta.xml
<CustomField>
    <fullName>Setup__c</fullName>
    <label>Setup</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stand Alone</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Retail/Hospitality</fullName>
                <isActive>false</isActive>
                <label>Retail/Hospitality</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/Acquiring_Fees_Lookup__mdt.object-meta.xml
<CustomObject>
    <description>Acquiring Fees - Davinder/Eoin</description>
    <label>Acquiring Fees Lookup</label>
    <pluralLabel>Acquiring Fees Lookup</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Max_Vol__c.field-meta.xml
<CustomField>
    <fullName>Max_Vol__c</fullName>
    <label>Max Vol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Min_Vol__c.field-meta.xml
<CustomField>
    <fullName>Min_Vol__c</fullName>
    <label>Min Vol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Minumum_Fees__c.field-meta.xml
<CustomField>
    <fullName>Minumum_Fees__c</fullName>
    <label>Minumum Fees</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POS/Online PBL</fullName>
                <default>true</default>
                <label>POS/Online PBL</label>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Online PBL</fullName>
            </value>
            <value>
                <fullName>Online Cybersource</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <label>Scheme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa/Mastercard</fullName>
                <default>true</default>
                <label>Visa/Mastercard</label>
            </value>
            <value>
                <fullName>Union Pay</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>Alipay</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
            <value>
                <fullName>Alipay/WeChat</fullName>
                <isActive>false</isActive>
                <label>Alipay/WeChat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Scheme_Fees__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Fees__c</fullName>
    <label>Scheme Fees</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Setup__c.field-meta.xml
<CustomField>
    <fullName>Setup__c</fullName>
    <label>Setup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stand Alone</fullName>
                <default>true</default>
                <label>Stand Alone</label>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality</fullName>
                <default>true</default>
                <label>Hospitality</label>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Retail/Hospitality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company_Sector__c.field-meta.xml
<CustomField>
    <fullName>Company_Sector__c</fullName>
    <description>Account Company Sector - requested by Finance on 24/1/22</description>
    <formula>TEXT(Account.Company_Sector__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Sector</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/x_AcquiringFeesLookupTest.cls
@IsTest
public class x_AcquiringFeesLookupTest {
  
	static void setup() {
  	}

    @IsTest
  	static void setFeesIfICPlusPlusFound() {

		//insert test account
        Account acc = new Account(name='Test');
      	acc.Owning_Country__c = 'United Kingdom';
        acc.Company_Sector__c = 'Retail';
        insert acc;
        
		//insert test opportunity
        Opportunity opp = new Opportunity(name='Test');
        opp.AccountId = acc.Id;
        opp.StageName = 'Opportunity Recorded';
        opp.CloseDate = Date.newInstance(2030, 12, 12);
        insert opp;

		//insert test Acquiring_Fees__c
        Acquiring_Fees__c aFee = new Acquiring_Fees__c();
        aFee.Vertical__c = 'Hospitality';
        aFee.Setup__c = 'Stand Alone';
        aFee.Platform__c = 'POS/Online PBL';
        aFee.Scheme__c = 'Visa/Mastercard';
        aFee.Acquiring_Volume__c = 6;
        aFee.Fees__c = '';
        aFee.Actual_Fees__c = 26.00;
        aFee.Opportunity__c = opp.Id;
        insert aFee;

        //lookup acquiring fees from the custom metadata type 'Acquiring Fees'
        List<Acquiring_Fees_Lookup__mdt> lstFees = new List<Acquiring_Fees_Lookup__mdt>();    
        lstFees = [SELECT Id, Platform__c, Scheme__c, Setup__c, Vertical__c, Scheme_Fees__c, Min_Vol__c, Max_Vol__c, Minumum_Fees__c, Min_Fees__c
                                        FROM Acquiring_Fees_Lookup__mdt
                                        WHERE Platform__c = :aFee.Platform__c
                                        AND Scheme__c = :aFee.Scheme__c
                                        AND Setup__c = :aFee.Setup__c
                                        AND Vertical__c = :aFee.Vertical__c
                           				AND Min_Vol__c <= :afee.Acquiring_Volume__c
                           				AND Max_Vol__c >= :afee.Acquiring_Volume__c
                                        LIMIT 1];        
        
        System.assertEquals('IC++: AF OF 25bps', lstFees[0].Minumum_Fees__c);
        
        List<Id> lstAFeesIds = new List<Id>();
        lstAFeesIds.add(aFee.Id);
        
        Test.startTest();
        
        //call method to set the Acquiring_Fees__c fees
        x_AcquiringFeesLookup.setFees(lstAFeesIds);
        
        //get Acquiring_Fees__c record to check update
        Acquiring_Fees__c aFeeTest = [SELECT Id, Fees__c
                           		FROM Acquiring_Fees__c 
                           		LIMIT 1];

        System.assertEquals('IC++: AF OF 25bps', aFeeTest.Fees__c);

        Test.stopTest();     

  	}

    @IsTest
  	static void setFeesIfICPlusPlusFoundBelowMinFees() {

		//insert test account
        Account acc = new Account(name='Test');
      	acc.Owning_Country__c = 'United Kingdom';
        acc.Company_Sector__c = 'Retail';
        insert acc;
        
		//insert test opportunity
        Opportunity opp = new Opportunity(name='Test');
        opp.AccountId = acc.Id;
        opp.StageName = 'Opportunity Recorded';
        opp.CloseDate = Date.newInstance(2030, 12, 12);
        insert opp;

		//insert test Acquiring_Fees__c
        Acquiring_Fees__c aFee = new Acquiring_Fees__c();
        aFee.Vertical__c = 'Hospitality';
        aFee.Setup__c = 'Stand Alone';
        aFee.Platform__c = 'POS/Online PBL';
        aFee.Scheme__c = 'Visa/Mastercard';
        aFee.Acquiring_Volume__c = 6;
        aFee.Fees__c = '';
        aFee.Actual_Fees__c = 24.00;
        aFee.Opportunity__c = opp.Id;
        insert aFee;

        //lookup acquiring fees from the custom metadata type 'Acquiring Fees'
        List<Acquiring_Fees_Lookup__mdt> lstFees = new List<Acquiring_Fees_Lookup__mdt>();    
        lstFees = [SELECT Id, Platform__c, Scheme__c, Setup__c, Vertical__c, Scheme_Fees__c, Min_Vol__c, Max_Vol__c, Minumum_Fees__c, Min_Fees__c
                                        FROM Acquiring_Fees_Lookup__mdt
                                        WHERE Platform__c = :aFee.Platform__c
                                        AND Scheme__c = :aFee.Scheme__c
                                        AND Setup__c = :aFee.Setup__c
                                        AND Vertical__c = :aFee.Vertical__c
                           				AND Min_Vol__c <= :afee.Acquiring_Volume__c
                           				AND Max_Vol__c >= :afee.Acquiring_Volume__c
                                        LIMIT 1];        
        
        System.assertEquals('IC++: AF OF 25bps', lstFees[0].Minumum_Fees__c);
        
        List<Id> lstAFeesIds = new List<Id>();
        lstAFeesIds.add(aFee.Id);
        
        Test.startTest();
        
        //call method to set the Acquiring_Fees__c fees
        x_AcquiringFeesLookup.setFees(lstAFeesIds);
        
        //get Acquiring_Fees__c record to check update
        Acquiring_Fees__c aFeeTest = [SELECT Id, Fees__c
                           		FROM Acquiring_Fees__c 
                           		LIMIT 1];

        System.assertEquals('IC++: AF OF 25bps', aFeeTest.Fees__c);

        Test.stopTest();     

  	}
    
    
    @IsTest
  	static void setFeesIfBlendedFound() {

		//insert test account
        Account acc = new Account(name='Test');
      	acc.Owning_Country__c = 'United Kingdom';
        acc.Company_Sector__c = 'Retail';
        insert acc;
        
		//insert test opportunity
        Opportunity opp = new Opportunity(name='Test');
        opp.AccountId = acc.Id;
        opp.StageName = 'Opportunity Recorded';
        opp.CloseDate = Date.newInstance(2030, 12, 12);
        insert opp;

		//insert test Acquiring_Fees__c
        Acquiring_Fees__c aFee = new Acquiring_Fees__c();
        aFee.Vertical__c = 'Hospitality';
        aFee.Setup__c = 'All';
        aFee.Platform__c = 'POS';
        aFee.Scheme__c = 'Union Pay';
        aFee.Acquiring_Volume__c = 11;
        aFee.Fees__c = '';
        aFee.Actual_Fees__c = 17.00;
        aFee.Opportunity__c = opp.Id;
        insert aFee;

        //lookup acquiring fees from the custom metadata type 'Acquiring Fees'
        List<Acquiring_Fees_Lookup__mdt> lstFees = new List<Acquiring_Fees_Lookup__mdt>();    
        lstFees = [SELECT Id, Platform__c, Scheme__c, Setup__c, Vertical__c, Scheme_Fees__c, Min_Vol__c, Max_Vol__c, Minumum_Fees__c, Min_Fees__c
                                        FROM Acquiring_Fees_Lookup__mdt
                                        WHERE Platform__c = :aFee.Platform__c
                                        AND Scheme__c = :aFee.Scheme__c
                                        AND Setup__c = :aFee.Setup__c
                                        AND Vertical__c = :aFee.Vertical__c
                           				AND Min_Vol__c <= :afee.Acquiring_Volume__c
                           				AND Max_Vol__c >= :afee.Acquiring_Volume__c
                                        LIMIT 1];        
        
        System.assertEquals('Blended: 1.60%', lstFees[0].Minumum_Fees__c);
        
        List<Id> lstAFeesIds = new List<Id>();
        lstAFeesIds.add(aFee.Id);
        
        Test.startTest();
        
        //call method to set the Acquiring_Fees__c fees
        x_AcquiringFeesLookup.setFees(lstAFeesIds);
        
        //get Acquiring_Fees__c record to check update
        Acquiring_Fees__c aFeeTest = [SELECT Id, Fees__c
                           		FROM Acquiring_Fees__c 
                           		LIMIT 1];

        System.assertEquals('Blended: 1.60%', aFeeTest.Fees__c);

        Test.stopTest();     

  	}
    
    
  

}