unpackaged/main/default/objects/Account/fields/Current_POS_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_POS_Contract_End_Date__c</fullName>
    <description>Hoist - Saurabh 20/01/22</description>
    <label>Current POS Contract End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Hotel_Current_Payment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Current_Payment_Provider__c</fullName>
    <description>Hoist</description>
    <label>Hotel Current Payment Provider</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/POS_System__c.field-meta.xml
<CustomField>
    <fullName>POS_System__c</fullName>
    <label>POS System (Terminal)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Owning_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Artema Hybrid</fullName>
            </value>
            <value>
                <fullName>Cardtech</fullName>
            </value>
            <value>
                <fullName>Concardis</fullName>
            </value>
            <value>
                <fullName>Easy Cash</fullName>
            </value>
            <value>
                <fullName>EFT930B Couleur (Réf 280)</fullName>
            </value>
            <value>
                <fullName>EFT930B Noir et blanc (Réf 270)</fullName>
            </value>
            <value>
                <fullName>EFT930B Noir et blanc (Réf 280)</fullName>
            </value>
            <value>
                <fullName>EFT930G Couleur (Réf 270)</fullName>
            </value>
            <value>
                <fullName>EFT930P (Réf 260)</fullName>
            </value>
            <value>
                <fullName>EFT930S (Réf 290)</fullName>
            </value>
            <value>
                <fullName>EFT930W Noir et Blanc (Réf 250)</fullName>
            </value>
            <value>
                <fullName>EFTSMART (Réf 320)</fullName>
            </value>
            <value>
                <fullName>EFTSMART (Réf 420)</fullName>
            </value>
            <value>
                <fullName>EFTSMART + PinPad avec carte (Réf 321)</fullName>
            </value>
            <value>
                <fullName>EFTSMART + PinPad avec insertion carte (Réf 421)</fullName>
            </value>
            <value>
                <fullName>EFTSMART + PinPad sans insertion carte (Réf 324)</fullName>
            </value>
            <value>
                <fullName>EFTSMART + PinPad sans insertion carte (Réf 424)</fullName>
            </value>
            <value>
                <fullName>Extenda</fullName>
            </value>
            <value>
                <fullName>Hypercom</fullName>
            </value>
            <value>
                <fullName>ICT220 PEM (Réf 100)</fullName>
            </value>
            <value>
                <fullName>ICT220 PEM + PinPad sans carte (Réf 104)</fullName>
            </value>
            <value>
                <fullName>ICT220 PEM PinPad carte (Réf 101)</fullName>
            </value>
            <value>
                <fullName>ICT220 PGEM (Réf 170)</fullName>
            </value>
            <value>
                <fullName>ICT220 PGEM + PP30S (Réf 174)</fullName>
            </value>
            <value>
                <fullName>ICT220 PGEM PinPad Carte</fullName>
            </value>
            <value>
                <fullName>ICT250 PEM + PinPad avec insertion carte (Réf 101_106)</fullName>
            </value>
            <value>
                <fullName>ICT250 PEM  + PPad sans insertion carte (Réf 104_109)</fullName>
            </value>
            <value>
                <fullName>ICT250 PEM Sans PinPad (Réf 100_105)</fullName>
            </value>
            <value>
                <fullName>ICT250 PGEM (Réf 170)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reason_Account_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_Account_On_Hold__c</fullName>
    <description>Hoist</description>
    <label>Reason Account On Hold</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Residual_Payments_Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Residual_Payments_Contract_End_Date__c</fullName>
    <description>Hoist - Saurabh 20/01/22</description>
    <label>Residual Payments Contract End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Upsales_AccID__c.field-meta.xml
<CustomField>
    <fullName>Upsales_AccID__c</fullName>
    <description>Hoist Updates</description>
    <label>Upsales AccID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/Hoist_Update__c.object-meta.xml
<CustomObject>
    <description>Used for Hoist weekly Updates</description>
    <label>Hoist Update</label>
    <nameField>
        <displayFormat>HOIST-{0000}</displayFormat>
        <label>Hoist Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hoist Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Hoist_Update__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <label>Batch</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/fields/current_Payments_contract_expiry__c.field-meta.xml
<CustomField>
    <fullName>current_Payments_contract_expiry__c</fullName>
    <label>current Payments contract expiry</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/fields/Current_Payments_provider_used__c.field-meta.xml
<CustomField>
    <fullName>Current_Payments_provider_used__c</fullName>
    <label>Current Payments provider used</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/fields/current_POS_contract_expiry__c.field-meta.xml
<CustomField>
    <fullName>current_POS_contract_expiry__c</fullName>
    <label>current POS contract expiry</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/fields/Current_POS_provider_used__c.field-meta.xml
<CustomField>
    <fullName>Current_POS_provider_used__c</fullName>
    <label>Current POS provider used</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/fields/Reason_Lost__c.field-meta.xml
<CustomField>
    <fullName>Reason_Lost__c</fullName>
    <label>Reason Lost</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/fields/Reason_on_Hold__c.field-meta.xml
<CustomField>
    <fullName>Reason_on_Hold__c</fullName>
    <label>Reason on Hold</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/fields/UpsalesAccId__c.field-meta.xml
<CustomField>
    <fullName>UpsalesAccId__c</fullName>
    <label>UpsalesAccId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Hoist_Update__c/fields/UpsalesOppId__c.field-meta.xml
<CustomField>
    <fullName>UpsalesOppId__c</fullName>
    <label>UpsalesOppId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Approved</fullName>
                <default>true</default>
                <label>Not Approved</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Reason_for_Loss__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Loss__c</fullName>
    <label>Reason for Loss</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Marketing Support</fullName>
            </value>
            <value>
                <fullName>Analytics Support</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Lack of integration to POS</fullName>
            </value>
            <value>
                <fullName>Bound to contract w existing Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <formula>IF (TEXT(StageName) = &quot;Opportunity Recorded&quot;, 0, 
IF (TEXT(StageName) = &quot;Prospect Qualified&quot;, 1, 
IF (TEXT(StageName) = &quot;Value Proposition Presented&quot;, 2, 
IF (TEXT(StageName) = &quot;Proposal Submitted&quot;, 3, 
IF (TEXT(StageName) = &quot;Contract Signed&quot;, 4, 
IF (TEXT(StageName) = &quot;Live&quot;, 4, 
IF (TEXT(StageName) = &quot;Proposal Lost&quot;, 0 , 0
)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Upsales_OppID__c.field-meta.xml
<CustomField>
    <fullName>Upsales_OppID__c</fullName>
    <description>Hoist</description>
    <label>Upsales OppID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/x_HoistUpdate.cls
public class x_HoistUpdate {

    public static final String PROPOSAL_SIGNED = 'Contract Signed';
    
    public static void processData(String strBatch)
    {
        
        
        //List of opportunities to update
        List<Opportunity> opportunities = new List<Opportunity>();
        //List of accounts to update
        List<Account> accounts = new List<Account>();
        //List of hoist_update__c to update
        List<Hoist_Update__c> hoistUpdates = new List<Hoist_Update__c>();
        
        Boolean hoistRecFound = false;

        //get the hoist update - new custom object where admin loads the weekly data
        List<Hoist_Update__c> lstHoistUpdateObjs = new List<Hoist_Update__c>();    
        
        lstHoistUpdateObjs = [SELECT Id, Batch__c, UpsalesAccId__c, UpsalesOppId__c, Stage__c,  Current_Payments_provider_used__c, current_Payments_contract_expiry__c,
                              Current_POS_provider_used__c, current_POS_contract_expiry__c, Reason_on_Hold__c, Reason_Lost__c
                            FROM Hoist_Update__c
                            WHERE Batch__c = :strBatch
                            ];
        
        //get list of UpsalesAccIds from the hoist updates
        List<String> lstHoistUpSalesAccIds = new List<String>();   
        for(Hoist_Update__c hoistId :lstHoistUpdateObjs){
        	lstHoistUpSalesAccIds.add(hoistId.UpsalesAccId__c);
        }
        
        //use the hoist accountids to find the account records
        List <Account> lstAccs = [SELECT Id, POS_System__c,Current_POS_Contract_End_Date__c,Hotel_Current_Payment_Provider__c, 
                                          Residual_Payments_Contract_End_Date__c,Reason_Account_On_Hold__c, Upsales_AccID__c 
                                      FROM Account 
                                      WHERE Upsales_AccID__c = :lstHoistUpSalesAccIds 
                                      ];        
        
        //get list of Account Ids from the hoist updates using the hoist account id
        List<String> lstHoistAccountIds = new List<String>();   
        for(Account acc :lstAccs){
        	lstHoistAccountIds.add(acc.Id);
        }
        
        //use the Account Ids to find the Opportunity records
        List <Opportunity> lstOpps = [SELECT Id, StageName, Upsales_OppID__c, Reason_for_Loss__c, AccountId 
                                      FROM Opportunity 
                                      WHERE AccountId = :lstHoistAccountIds 
                                      ];
        
    
		//loop through updates        
        for(Hoist_Update__c hoistUpdate :lstHoistUpdateObjs){
            
            hoistRecFound = false;
            
            //may not have a hoist opp id, so need to find the account
            for(Account hoistAcc :lstAccs){
                if(hoistAcc.Upsales_AccID__c == hoistUpdate.UpsalesAccId__c){
                    
                    hoistRecFound = true;
                    
                    //update Account fields
                            
                    //picklist
                    hoistAcc.POS_System__c = hoistUpdate.Current_POS_provider_used__c;
                    //date
                    hoistAcc.Current_POS_Contract_End_Date__c = hoistUpdate.current_POS_contract_expiry__c;
                    //text
                    hoistAcc.Hotel_Current_Payment_Provider__c = hoistUpdate.Current_Payments_provider_used__c;
                    //date
                    hoistAcc.Residual_Payments_Contract_End_Date__c = hoistUpdate.current_Payments_contract_expiry__c;
                    //text
                    hoistAcc.Reason_Account_On_Hold__c = hoistUpdate.Reason_on_Hold__c;
                            
                    accounts.add(hoistAcc);                    
                    
                    for(Opportunity hoistOpp :lstOpps){
                        //only update opportunity if stage is not already Proposal Signed
                    	if((hoistOpp.AccountId == hoistAcc.Id) && (hoistOpp.StageName != PROPOSAL_SIGNED)){
                            //update the related opp
                            
                        	//convert the stage - picklist
                        	String sfStage = convertStage(hoistUpdate.Stage__c);
                        	if(sfStage != null){
                            	hoistOpp.StageName = sfStage;                            
                            	//update the hoist status so that final finance approval fires
                            	if (sfStage == PROPOSAL_SIGNED){
                                	//also set the status
                                	hoistOpp.Approval_Status__c = 'Approved';
                            	}  
                                
                                if (hoistUpdate.UpsalesOppId__c != null){
                                    //update the opportunity upsalesoppid
                                	hoistOpp.Upsales_OppID__c = hoistUpdate.UpsalesOppId__c;
                                }
                                
                                //update Reason Lost - picklist
                    			hoistOpp.Reason_for_Loss__c = hoistUpdate.Reason_Lost__c;
                        	} 

                            //** update upsales opp id
                    	    opportunities.add(hoistOpp);
                        }                                     

                    }   //opp 
              
                }	//if
            
            }//acc
            
            if(hoistRecFound == false){
                hoistUpdate.Notes__c = 'UpsalesID Not Found';
            }else
            {
                hoistUpdate.Notes__c = 'UpsalesID Found';
            }
            hoistUpdates.add(hoistUpdate);
            
        }
            
        update opportunities;
        update accounts;
        update hoistUpdates;
    }   
    
    //converts the stage
   	public static String convertStage(String hoistStage) {
    	String strStage = null;
        
        //updated 22/6/22 for stage renames
        switch on hoistStage{
            when 'Prospect Research'{
                strStage = 'Opportunity Recorded'; 
            }
            when 'Qualification'{
                strStage = 'Prospect Qualified'; 
            }
            when 'Needs Analysis'{
                strStage = 'Value Proposition Presented';  
            }
            when 'Quotation'{
                strStage = 'Proposal Submitted'; 
            }
            when 'Closing'{
                strStage = 'Proposal Submitted'; 
            }
            when 'Won'{
                strStage = 'Contract Signed'; 
            }
            when 'Lost'{
                strStage = 'Proposal Lost'; 
            }
            when 'On Hold'{
                strStage = 'Proposal Lost'; 
            }
            when else{
                
            }
        }
        
        return strStage;


    }

}