unpackaged/main/default/objects/Lead/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Company Acquisition</fullName>
            </value>
            <value>
                <fullName>Cultural &amp; Sales Training</fullName>
            </value>
            <value>
                <fullName>Currency Conversion for Acquirers</fullName>
            </value>
            <value>
                <fullName>Data &amp; Insights</fullName>
            </value>
            <value>
                <fullName>eCommerce Merchant solutions</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Payment Gateway</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Payments - ACH</fullName>
            </value>
            <value>
                <fullName>POS Merchant solutions</fullName>
            </value>
            <value>
                <fullName>Tax Free</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Client Cross Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/spam__c.field-meta.xml
<CustomField>
    <fullName>spam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>spam</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/x_RunAssignmentRulesTest.cls
@isTest
public class x_RunAssignmentRulesTest {

    @testSetup
    static void loadData(){
        Lead l = new Lead(
            LastName='Test',
            Company='Test',
            Country = 'United Kingdom',
            LeadSource = 'Web',
            Lead_Type__c = 'Tax Free',
            spam__c = false
        );
        insert l;
    }
    
    @isTest
    static void testLead(){
        //instantiate List to pass to @InvocableMethod
        List<Id> ids = new List<Id>();
        
        //query for test data and add to List
        Lead l = [SELECT Id, OwnerId FROM Lead];
        ids.add(l.Id);
        
        //call @InvocableMethod
        test.startTest();
        x_RunAssignmentRules.assignLeads(ids);
        test.stopTest();
        
        //verify that Lead was re-assigned
        Lead res = [SELECT Id, OwnerId FROM Lead];
        //System.assert(l.OwnerId != res.OwnerId, res);
    }
}