unpackaged/main/default/objects/Lead/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Company Acquisition</fullName>
            </value>
            <value>
                <fullName>Cultural &amp; Sales Training</fullName>
            </value>
            <value>
                <fullName>Currency Conversion for Acquirers</fullName>
            </value>
            <value>
                <fullName>Data &amp; Insights</fullName>
            </value>
            <value>
                <fullName>eCommerce Merchant solutions</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Payment Gateway</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Payments - ACH</fullName>
            </value>
            <value>
                <fullName>POS Merchant solutions</fullName>
            </value>
            <value>
                <fullName>Tax Free</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Client Cross Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/spam__c.field-meta.xml
<CustomField>
    <fullName>spam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>spam</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead_Spam_Company__c/Lead_Spam_Company__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Lead Spam Companies</label>
</CustomObject>

unpackaged/main/default/classes/x_TriggerHandlerLeadTest.cls
@isTest
public class x_TriggerHandlerLeadTest {
	static void setup() {
  	}
    
  	@IsTest
  	static void testMarkSpam() {
      
		Lead newLead = new Lead();
      	newLead.LastName = 'Test';
      	newLead.Company = 'google';
      	newLead.Lead_Type__c = 'Tax Free';
      	newLead.Status = 'Open';
        newLead.spam__c = true;
        newLead.Country = 'United Kingdom';
        insert newLead;
        
        List<Lead> leads =[select id,company from Lead where id=: newLead.id];
    	System.assertEquals(1, leads.size()); 

        Lead_Spam_Company__c newCustomSetting = new Lead_Spam_Company__c();
      	newCustomSetting.Name = '1';
      	newCustomSetting.Company__c = 'google';
		insert newCustomSetting;       
        
        List<Lead_Spam_Company__c> lstSpamCompanies = Lead_Spam_Company__c.getall().values();
    	System.assertEquals(1, lstSpamCompanies.size());

        Test.startTest();
        
        for(Integer i = 0; i < leads.size(); i++){
            //cycle through the lead spam companies (custom settings)
            for(Integer j = 0; j < lstSpamCompanies.size(); j++){
                if (lstSpamCompanies[j].Company__c == leads[i].company){
                    //set the spam checkbox
                    leads[i].spam__c = true;
                    System.assertEquals(true, leads[i].spam__c);
                }
            }        
        } 
        
        Test.stopTest();
        
  	}     
}