unpackaged/main/default/objects/Acquiring_Fees__c/Acquiring_Fees__c.object-meta.xml
<CustomObject>
    <label>Acquiring Fees</label>
    <nameField>
        <displayFormat>AF-{0000}</displayFormat>
        <label>Acquiring Fees Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acquiring Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Acquiring_Volume__c.field-meta.xml
<CustomField>
    <fullName>Acquiring_Volume__c</fullName>
    <inlineHelpText>Enter value in Millions i.e 1000000 should be entered as 1</inlineHelpText>
    <label>Acquiring Volume (Millions)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Actual_Fee_Per_Click__c.field-meta.xml
<CustomField>
    <fullName>Actual_Fee_Per_Click__c</fullName>
    <inlineHelpText>Fee per click for all Verticals</inlineHelpText>
    <label>Actual Fee Per Click</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Actual_Fees__c.field-meta.xml
<CustomField>
    <fullName>Actual_Fees__c</fullName>
    <inlineHelpText>Enter actual Fees as a whole number i.e. for the bps value &#39;IC++: AF OF 25bps&#39;, enter 25, and for the value &#39;Blended: 1.60%&#39; enter 1.6</inlineHelpText>
    <label>Actual Fees</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <label>Minimum Fees</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Fees_Require_Approval__c.field-meta.xml
<CustomField>
    <fullName>Fees_Require_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fees Require Approval</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Click Per Fee Margin</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/No_of_Transactions__c.field-meta.xml
<CustomField>
    <fullName>No_of_Transactions__c</fullName>
    <label>No of Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Acquiring Fees</relationshipLabel>
    <relationshipName>Acquiring_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Setup__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POS/Online PBL</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Online PBL</fullName>
            </value>
            <value>
                <fullName>Online Cybersource</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <label>Scheme</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Platform__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa/Mastercard</fullName>
            </value>
            <value>
                <fullName>Union Pay</fullName>
            </value>
            <value>
                <fullName>Alipay</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>Alipay/WeChat</fullName>
                <isActive>false</isActive>
                <label>Alipay/WeChat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Setup__c.field-meta.xml
<CustomField>
    <fullName>Setup__c</fullName>
    <label>Setup</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stand Alone</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Transaction_Fees__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Fees__c</fullName>
    <label>Transaction Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Retail/Hospitality</fullName>
                <isActive>false</isActive>
                <label>Retail/Hospitality</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/Acquiring_Fees_Lookup__mdt.object-meta.xml
<CustomObject>
    <description>Acquiring Fees - Davinder/Eoin</description>
    <label>Acquiring Fees Lookup</label>
    <pluralLabel>Acquiring Fees Lookup</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Max_Vol__c.field-meta.xml
<CustomField>
    <fullName>Max_Vol__c</fullName>
    <label>Max Vol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Min_Fees__c.field-meta.xml
<CustomField>
    <fullName>Min_Fees__c</fullName>
    <label>Min Fees</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Min_Vol__c.field-meta.xml
<CustomField>
    <fullName>Min_Vol__c</fullName>
    <label>Min Vol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Minumum_Fees__c.field-meta.xml
<CustomField>
    <fullName>Minumum_Fees__c</fullName>
    <label>Minumum Fees</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POS/Online PBL</fullName>
                <default>true</default>
                <label>POS/Online PBL</label>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>Online PBL</fullName>
            </value>
            <value>
                <fullName>Online Cybersource</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <label>Scheme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visa/Mastercard</fullName>
                <default>true</default>
                <label>Visa/Mastercard</label>
            </value>
            <value>
                <fullName>Union Pay</fullName>
            </value>
            <value>
                <fullName>Amex</fullName>
            </value>
            <value>
                <fullName>Alipay</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
            <value>
                <fullName>Alipay/WeChat</fullName>
                <isActive>false</isActive>
                <label>Alipay/WeChat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Scheme_Fees__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Fees__c</fullName>
    <label>Scheme Fees</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Setup__c.field-meta.xml
<CustomField>
    <fullName>Setup__c</fullName>
    <label>Setup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stand Alone</fullName>
                <default>true</default>
                <label>Stand Alone</label>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Transaction_Fee__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Fee__c</fullName>
    <label>Transaction Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Acquiring_Fees_Lookup__mdt/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hospitality</fullName>
                <default>true</default>
                <label>Hospitality</label>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Retail/Hospitality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fees_Require_Approval__c.field-meta.xml
<CustomField>
    <fullName>Fees_Require_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fees Require Approval</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Transaction_Fee__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Fee__c</fullName>
    <label>Transaction Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/x_AcquiringFeesLookup.cls
/**
 * @description       : 
 * @author            : Mickey
 * @group             : 
 * @last modified on  : 7-7-2022
 * @last modified by  : Mickey (updated fee approval check)
**/

public class x_AcquiringFeesLookup {

    public static final String AMEX = 'Amex';
    public static final String PARKING = 'Parking';
    public static final String HOSPITALITY = 'Hospitality';
    public static final String RETAIL = 'Retail';
    public static final String NO_FEES_FOUND = 'No Fees found that match criteria entered.  No Profit calculated.';
    public static final String NO_FEES_PARKING = 'No minimum fees relevant to Parking.';
    
    @InvocableMethod(label='Acquiring Fees Lookup' description='Acquiring Fees Lookup')
    public static void setFees(list<id> listofaFeesId)
    {

        // Get acquiring fees
        //get Acquiring_Fees__c record using id from process
        List<Acquiring_Fees__c> afees = [SELECT Name, Id, Platform__c, Scheme__c, Setup__c, Vertical__c, Acquiring_Volume__c, Fees__c, 
                                                Actual_Fees__c, Profit__c, Opportunity__c, Actual_Fee_Per_Click__c, No_of_Transactions__c, CurrencyIsoCode
                                        FROM Acquiring_Fees__c 
                                        WHERE Id In:listofaFeesId];

        //lookup acquiring fees from the custom metadata type 'Acquiring Fees Lookup'
        List<Acquiring_Fees_Lookup__mdt> lstLookup = [SELECT Id, Platform__c, Scheme__c, Setup__c, Vertical__c, Scheme_Fees__c, Min_Vol__c, Max_Vol__c, 
                                                             Minumum_Fees__c, Min_Fees__c, Transaction_Fee__c
                                                      FROM Acquiring_Fees_Lookup__mdt];

        //get the currecy conversion rate from user entered currency
        Decimal cts = [SELECT Id, IsoCode, ConversionRate FROM CurrencyType WHERE IsoCode = :afees[0].CurrencyIsoCode LIMIT 1].ConversionRate;
        
        Boolean bFeeFound = false;
        Boolean bClickPerFee = false;
        Boolean bApprovalRequired = false;
        Decimal dFee = 0.0;
        Decimal margin = 0.0;
        
        // New Opp object
        Opportunity varOpp = new Opportunity();

        for(Acquiring_Fees__c afee :afees)
        {
            //user for currency conversion to EUR
            Decimal convertedVolume;
            
            //set Opportunity
            varOpp.Id = afee.Opportunity__c;
    
            for(Acquiring_Fees_Lookup__mdt curLookup : lstLookup) 
            {
                    
				//do currency conversion here
                if (afee.CurrencyIsoCode != 'EUR'){
                	convertedVolume = afee.Acquiring_Volume__c / cts;
                }else{
                    //EUR (*1)
                    convertedVolume = afee.Acquiring_Volume__c; 
                }
                    
                //convert to euro before doing lookup
                        
                if(curLookup.Platform__c == afee.Platform__c & 
                   curLookup.Scheme__c == afee.Scheme__c & 
                   curLookup.Setup__c == afee.Setup__c & 
                   curLookup.Vertical__c == afee.Vertical__c & 
                   curLookup.Min_Vol__c <= convertedVolume &
                   curLookup.Max_Vol__c >= convertedVolume)
                {
                	//lookup found
                    bFeeFound = true;
                        
                    //do check for click per fee here (non parking)
		            if (((afee.Vertical__c == HOSPITALITY) || (afee.Vertical__c == RETAIL)) && (afee.Actual_Fees__c == null)){
						bClickPerFee = true;
                            
                        //calcluate margin for the fee lookup check
                        //calculate the profit
                        margin = calculateMargin(afee);
                            
					}else{
                            
                    	dFee = afee.Actual_Fees__c;
                        if(curLookup.Scheme_Fees__c != null){
                        	//blended
                            dFee = dFee/100;
                        }else{
                       		if(afee.Scheme__c != AMEX){
                            	//IC++
                                dFee = dFee/10000;
                            }
                        }
						margin = dfee; //used in check later
                    }
                        
					//catch here if users entered a volume bigger than 1000 million.  They could have entered '5000000' instead of '5'
                    //when trying to enter 5 million.  They can then edit and avoid approvals
                    if (convertedVolume > 1000){
	                	afee.Fees__c = curLookup.Minumum_Fees__c + '. Since your Acquired Volume exceeds 1000 Million, approval is required. ' +
                                    			'Check that you entered the volume correctly i.e. 1 million should be entered as 1 and not 1000000';
                        afee.Fees_Require_Approval__c = true; 
                        //varOpp.Fees_Require_Approval__c = true;                            
                    }else{
                            
						//this actual fees need divided by 10000
                        if (curLookup.Min_Fees__c <= margin){
                        	//fees found and above the minimum
                            afee.Fees__c = curLookup.Minumum_Fees__c;
                            afee.Fees_Require_Approval__c = false;
                                                
						} else{
                        	//fees found and below the minimum
                            afee.Fees__c = curLookup.Minumum_Fees__c;
                            afee.Fees_Require_Approval__c = true; 
                                            
                        }
                            
					}
                        
                    if (bClickPerFee){
						afee.Profit__c = afee.Actual_Fee_Per_Click__c * afee.No_of_Transactions__c;
                        afee.Margin__c = margin;
					}else{
                        afee.Margin__c = null;    //only for click per fee
						//calculate the profit
                        Decimal profit = calculateProfit(bFeeFound, afee, curLookup);
                        afee.Profit__c = profit;
            
                        Decimal txfees = calculateTransactionFees(bFeeFound, afee, curLookup);
                        afee.Transaction_Fees__c = txfees;
                            
                    }
				} 
            }

            if (!bFeeFound){
				//no fees found in custom metadata matrix
                //reset
                bFeeFound = false;
                afee.Transaction_Fees__c = 0.00;
                    
                //new parking reqmt - 9/9/21
                if (afee.Vertical__c == PARKING) {
                	if (afee.Actual_Fees__c != null){
                    	//calculate based on volume and actual fees
                     	afee.Profit__c = ((afee.Acquiring_Volume__c * 1000000) * (afee.Actual_Fees__c/100)) ;   
                    }    
                    else if(afee.Actual_Fee_Per_Click__c != null){
                        //calculate based on actual fee per click and no of transactions
	                  	afee.Profit__c = (afee.No_of_Transactions__c * afee.Actual_Fee_Per_Click__c);
                    }
                     
                    afee.Fees__c = NO_FEES_PARKING;
                    afee.Fees_Require_Approval__c = false;
                     
                }
               	else{
	                afee.Profit__c = 0.00;                    
                   	afee.Fees__c = NO_FEES_FOUND;
                   	afee.Fees_Require_Approval__c = true;
               	}
                    
       		}

        }

        //update acquring fees
        update afees;
        
        //update parent opportunity - check if any child cquiring Fee record needs approval
        bApprovalRequired = checkIfApprovalNeeded(varOpp);
        if (bApprovalRequired){
            varOpp.Fees_Require_Approval__c = true;
        }else{
            varOpp.Fees_Require_Approval__c = false;
        }
        update varOpp;    
            
        
    }
    
    public static Boolean checkIfApprovalNeeded(Opportunity varOpp){
        Boolean bApproval = false;
        
        List<Acquiring_Fees__c> afeeApprovals = [SELECT Id, Fees_Require_Approval__c
                                        		FROM Acquiring_Fees__c 
                                        		WHERE Opportunity__c = :varOpp.Id
                                                AND Fees_Require_Approval__c = true 
                                                ];
        If (afeeApprovals.size() > 0) {
            bApproval = true;
        }
        
        return bApproval;
    }
    
   	public static Decimal calculateProfit(Boolean bFeeFound, Acquiring_Fees__c fees, Acquiring_Fees_Lookup__mdt lookupFees) {
        
        Decimal profit = 0.0;

        if (bFeeFound){
            if(lookupFees.Scheme_Fees__c != null){
                //blended
                    
                Decimal dActualFee = fees.Actual_Fees__c;
                dActualFee = dActualFee/100;
                Decimal dSchemeFee = lookupFees.Scheme_Fees__c;
                Decimal mltply = dActualFee - dSchemeFee;
                Decimal vol = fees.Acquiring_Volume__c;
                    
                profit = (vol * mltply) * 1000000;
            } else {
                if(fees.Scheme__c == AMEX){
                    //Amex
                    profit = (fees.Acquiring_Volume__c * fees.Actual_Fees__c) * 1000000;
                }else{
                    //IC++
                    profit = (fees.Acquiring_Volume__c * fees.Actual_Fees__c) * 100;
                }
            }
        }
        
        return profit;
    }

   	public static Decimal calculateTransactionFees(Boolean bFeeFound, Acquiring_Fees__c fees, Acquiring_Fees_Lookup__mdt lookupFees) {
        
        Decimal transactionFees = 0.0;

        if (bFeeFound){
            if((lookupFees.Transaction_Fee__c != null) && (fees.No_of_Transactions__c != null)){
                //transaction fee included
                transactionFees = fees.No_of_Transactions__c * lookupFees.Transaction_Fee__c;
            }
        }
        
        return transactionFees;
    }
    
   	public static Decimal calculateMargin(Acquiring_Fees__c fees) {
        
        Decimal revenue = 0.0;
        Decimal margin = 0.0;
        
        if((fees.Actual_Fee_Per_Click__c != null) && (fees.No_of_Transactions__c != null)){
            revenue = fees.Actual_Fee_Per_Click__c * fees.No_of_Transactions__c;
	        margin = (revenue / (fees.Acquiring_Volume__c * 1000000))*100;
        }
        
        return margin;
    }    

}