unpackaged/main/default/objects/POS_Solution__c/POS_Solution__c.object-meta.xml
<CustomObject>
    <label>POS Solution</label>
    <nameField>
        <displayFormat>POS-{00000}</displayFormat>
        <label>POS Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POS Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/POS_Solution__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>POS Solutions</relationshipLabel>
    <relationshipName>POS_Solutions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Associated_Owner__c.field-meta.xml
<CustomField>
    <fullName>Associated_Owner__c</fullName>
    <label>Associated Owner</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Comms_Type__c.field-meta.xml
<CustomField>
    <fullName>Comms_Type__c</fullName>
    <label>Comms Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Comms_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Elavon_TID__c.field-meta.xml
<CustomField>
    <fullName>Elavon_TID__c</fullName>
    <label>Elavon TID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/EMV_Online_Keys__c.field-meta.xml
<CustomField>
    <fullName>EMV_Online_Keys__c</fullName>
    <label>EMV Online Keys</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Firmware_Version__c.field-meta.xml
<CustomField>
    <fullName>Firmware_Version__c</fullName>
    <label>Firmware Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/HDW_Version__c.field-meta.xml
<CustomField>
    <fullName>HDW_Version__c</fullName>
    <label>HDW Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/IP_Address__c.field-meta.xml
<CustomField>
    <fullName>IP_Address__c</fullName>
    <label>IP Address</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Passport_Scanner__c.field-meta.xml
<CustomField>
    <fullName>Passport_Scanner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passport &amp; CC Scanner</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/PCI_PTS_Approval_number__c.field-meta.xml
<CustomField>
    <fullName>PCI_PTS_Approval_number__c</fullName>
    <label>PCI PTS Approval number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/PCI_PTS_POI_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>PCI_PTS_POI_Product_Type__c</fullName>
    <label>PCI PTS POI Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/PCI_PTS_Standard_version__c.field-meta.xml
<CustomField>
    <fullName>PCI_PTS_Standard_version__c</fullName>
    <label>PCI PTS Standard version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>IF(Account__r.Phone = &quot;&quot;, &quot;+44 845 129 8993&quot;, Account__r.Phone)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Pinpad__c.field-meta.xml
<CustomField>
    <fullName>Pinpad__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pinpad</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Planned_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Install_Date__c</fullName>
    <label>Planned Install Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Planned_Rollout_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Rollout_Date__c</fullName>
    <label>Planned Rollout Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Post_Code__c</fullName>
    <formula>Account__r.BillingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Post Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Primary_DNS__c.field-meta.xml
<CustomField>
    <fullName>Primary_DNS__c</fullName>
    <label>Primary DNS</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Print_Return_Label__c.field-meta.xml
<CustomField>
    <fullName>Print_Return_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Print Return Label</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Printer__c.field-meta.xml
<CustomField>
    <fullName>Printer__c</fullName>
    <label>Printer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Epson TM M30 Thermal</fullName>
            </value>
            <value>
                <fullName>Epson TM T20 I (T80)</fullName>
            </value>
            <value>
                <fullName>Epson TM T20 II (T80)</fullName>
            </value>
            <value>
                <fullName>Epson TM T20 III Thermal</fullName>
            </value>
            <value>
                <fullName>Epson TM T88</fullName>
            </value>
            <value>
                <fullName>Epson TM T88IV (T80)</fullName>
            </value>
            <value>
                <fullName>Epson TM T88V (T80)</fullName>
            </value>
            <value>
                <fullName>Epson TM U295 (Impact)</fullName>
            </value>
            <value>
                <fullName>Laserpro P1102W</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>STAR TSP 700 Thermal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Printing_Format__c.field-meta.xml
<CustomField>
    <fullName>Printing_Format__c</fullName>
    <label>Printing Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Thermal</fullName>
            </value>
            <value>
                <fullName>DINA-4</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Proposed_Solution__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Solution__c</fullName>
    <label>Proposed Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Solutions</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Proposed_Solution_Store__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Solution_Store__c</fullName>
    <formula>TEXT(Account__r.Proposed_Solution__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proposed Solution Store</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/PTS_Application_Version__c.field-meta.xml
<CustomField>
    <fullName>PTS_Application_Version__c</fullName>
    <label>PTS Application Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Reference_ID__c.field-meta.xml
<CustomField>
    <fullName>Reference_ID__c</fullName>
    <formula>Account__r.Reference_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reference ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/POS_Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Solutions</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{000000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units (Account)</relationshipLabel>
    <relationshipName>Units1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Firmware_Version__c.field-meta.xml
<CustomField>
    <fullName>Firmware_Version__c</fullName>
    <label>Firmware Version</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Owning_Country__c.field-meta.xml
<CustomField>
    <fullName>Owning_Country__c</fullName>
    <label>Associated Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>British Virgin Islands</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Cyprus</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Iceland</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malta</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Monaco</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Puerto Rico</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Saint Barthelemy</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/PCI_PTS_Approval_Number__c.field-meta.xml
<CustomField>
    <fullName>PCI_PTS_Approval_Number__c</fullName>
    <label>PCI PTS Approval Number</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/PCI_PTS_POI_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>PCI_PTS_POI_Product_Type__c</fullName>
    <label>PCI PTS POI Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OEM PED</fullName>
            </value>
            <value>
                <fullName>OEM SCR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/POS_Solution__c.field-meta.xml
<CustomField>
    <fullName>POS_Solution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>POS Solution</label>
    <referenceTo>POS_Solution__c</referenceTo>
    <relationshipLabel>Passport Scanner &amp; Printer Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/PTS_Application_Version__c.field-meta.xml
<CustomField>
    <fullName>PTS_Application_Version__c</fullName>
    <label>PTS Application Version</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Comms_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PSTN</fullName>
    </customValue>
    <customValue>
        <fullName>WiFi</fullName>
    </customValue>
    <customValue>
        <fullName>IP</fullName>
    </customValue>
    <customValue>
        <fullName>BT IP</fullName>
    </customValue>
    <customValue>
        <fullName>BT PSTN</fullName>
    </customValue>
    <customValue>
        <fullName>3G</fullName>
    </customValue>
    <customValue>
        <fullName>4G</fullName>
    </customValue>
    <customValue>
        <fullName>GPRS</fullName>
    </customValue>
    <customValue>
        <fullName>Not Required</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>WiFi + SIM</fullName>
    </customValue>
    <masterLabel>Comms Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VAT</fullName>
    </customValue>
    <customValue>
        <fullName>VAT &amp; Payments</fullName>
    </customValue>
    <customValue>
        <fullName>VAT &amp; Payments &amp; DCC</fullName>
    </customValue>
    <customValue>
        <fullName>VAT &amp; Token</fullName>
    </customValue>
    <customValue>
        <fullName>Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Payments &amp; DCC</fullName>
    </customValue>
    <customValue>
        <fullName>Refunding Non Cash</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Solutions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>Elavon</fullName>
    </customValue>
    <customValue>
        <fullName>Global Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Kiosk</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <customValue>
        <fullName>PA</fullName>
    </customValue>
    <customValue>
        <fullName>PA 3rd Party</fullName>
    </customValue>
    <customValue>
        <fullName>PAOL</fullName>
    </customValue>
    <customValue>
        <fullName>PAX</fullName>
    </customValue>
    <customValue>
        <fullName>PAX Payments</fullName>
    </customValue>
    <customValue>
        <fullName>Pay By Link</fullName>
    </customValue>
    <customValue>
        <fullName>PC</fullName>
    </customValue>
    <customValue>
        <fullName>PD</fullName>
    </customValue>
    <customValue>
        <fullName>PI</fullName>
    </customValue>
    <customValue>
        <fullName>PI (AX Integration)</fullName>
    </customValue>
    <customValue>
        <fullName>PI (Elavon)</fullName>
    </customValue>
    <customValue>
        <fullName>PII</fullName>
    </customValue>
    <customValue>
        <fullName>Planet Pay on Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Planet Pay on PAX</fullName>
    </customValue>
    <customValue>
        <fullName>POL</fullName>
    </customValue>
    <customValue>
        <fullName>POL Pro</fullName>
    </customValue>
    <customValue>
        <fullName>POL Pro PAX</fullName>
    </customValue>
    <customValue>
        <fullName>PT</fullName>
    </customValue>
    <customValue>
        <fullName>PTF</fullName>
    </customValue>
    <customValue>
        <fullName>PT PAX</fullName>
    </customValue>
    <customValue>
        <fullName>TBD</fullName>
    </customValue>
    <customValue>
        <fullName>Pay @ Counter</fullName>
    </customValue>
    <customValue>
        <fullName>Pay @ Table</fullName>
    </customValue>
    <customValue>
        <fullName>Pay @ Reception</fullName>
    </customValue>
    <customValue>
        <fullName>Planet Connect Mobility</fullName>
    </customValue>
    <masterLabel>Solutions</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/POS_Solution_GetFlowRecords.cls
/**
 * @description       : 
 * @author            : Florin Galea
 * @group             : 
 * @last modified on  : 03-03-2022
 * @last modified by  : Florin Galea
**/
public with sharing class POS_Solution_GetFlowRecords {
    //this invocable method takes a collection of ids from Flow from a record variable
    //and returns a list of lists of POS Solutions.
    //the list of lists is stored as a collection variable in the Flow.
    @InvocableMethod (label = 'Fetch Selected POS Solutions' description = 'returns lis of POS Solutions from collection of IDs.')
    
    //this method returns a List of Lists of POS Solutions to the flow and receives a List of Lists of Ids
    public static List<List<POS_Solution__c>> getPOSSolutions (List<List<String>> listOfIds) {
        List<String> theStringList = listOfIds.get(0);
        //Fetch all fields from 
        List<POS_Solution__c> posSolutions = [SELECT Account_Name__c,
                                                Account__c,
                                                //Associated_Owner__c,
                                                Comments__c,
                                                Comms_Type__c,
                                                //Deployment_Date__c,
                                                //EMV_Online_Keys__c,
                                                Elavon_TID__c,
                                                Firmware_Version__c,
                                                HDW_Version__c,
                                                IP_Address__c,
                                                Id,
                                                Name,
                                                OwnerId,
                                                Owning_Country__c,
                                                PCI_PTS_Approval_number__c,
                                                PCI_PTS_POI_Product_Type__c,
                                                PCI_PTS_Standard_version__c,
                                                PO_Number__c,
                                                PTS_Application_Version__c,
                                                Passport_Scanner__c,
                                                Password__c,
                                                Phone__c,
                                                Pinpad__c,
                                                Planned_Install_Date__c,
                                                Planned_Rollout_Date__c,
                                                Position__c,
                                                Post_Code__c,
                                                Primary_DNS__c,
                                                Print_Return_Label__c,
                                                Printer__c,
                                                Printing_Format__c,
                                                Product__c,
                                                Proposed_Solution_Store__c,
                                                Proposed_Solution__c,
                                                Province__c,
                                                Purchase_Date__c,
                                                //RecordTypeId,
                                                Reference_ID__c,
                                                Reference_or_Account_ID__c,
                                                Refund_Method_Obligatory__c,
                                                Return_Description__c,
                                                Return_Type__c,
                                                Rolled_Out__c,
                                                Rollout_Complete__c,
                                                SIM_Number__c,
                                                SS_DS_TRS_only__c,
                                                Secondary_DNS__c,
                                                Send_Fallback_Online_Email__c,
                                                Service_Type__c,
                                                Shipment_Type__c,
                                                Shop_Name__c,
                                                Shop_Owner__c,
                                                Software_Version__c,
                                                Solution_Delivery_Date__c,
                                                Solution_Rolled_Out__c,
                                                Solution__c,
                                                Static_IP__c,
                                                Status__c,
                                                TMS_TID__c,
                                                Tracking_Number__c,
                                                //Unit_Status__c,
                                                Unit__c,
                                                X3C_Instance_TID__c
                                FROM POS_Solution__c
                                WHERE Id 
                                IN :theStringList]; 
        //declare a new list of lists of POS Solutions
        List<List<POS_Solution__c>> itemListList = new List<List<POS_Solution__c>>();
        System.debug(posSolutions.size());
        //add the list of POS Solutions to the list of lists
        itemListList.add(posSolutions);
        System.debug(itemListList.size());
        // send list of lists to the Flow	
        return itemListList;        
    }  
}