unpackaged/main/default/objects/Tax_Free_Form__c/Tax_Free_Form__c.object-meta.xml
<CustomObject>
    <label>Tax Free Form</label>
    <nameField>
        <label>Tax Free Form Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Free Form</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tax_Free_Form__c/fields/Tourist__c.field-meta.xml
<CustomField>
    <fullName>Tourist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tourist</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Tourist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tax Free Form (Tourist)</relationshipLabel>
    <relationshipName>Tourist</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/New_Tourist_Form_Ctrl.cls
public class New_Tourist_Form_Ctrl {
    
    public String ttfId{get;set;}
    public String touristVal;
    public Boolean displayError{get;set;}
    public Account acc{get;set;}
    public String accFstName{get;set;}
    public String accLstName{get;set;}
    public Tax_Free_Form__c tff_Rec{get;set;}
    
    public New_Tourist_Form_Ctrl(ApexPages.StandardController controller){
        ttfId = ApexPages.currentPage().getParameters().get('ttfId');
        if(ttfId != null){
            tff_Rec = [select Tourist__c from Tax_Free_Form__c WHERE Id = :ttfId];
        }
        acc = new Account();
    }
    
    public PageReference saveAcc(){
        PageReference pageRef;
        try{
            Id touristRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Tourist').getRecordTypeId();
            acc.FirstName = accFstName;
            acc.LastName = accLstName;
            acc.RecordTypeId = touristRecordTypeId;
            insert acc;
            Tax_Free_Form__c ttfLst = [SELECT Id, Tourist__c FROM Tax_Free_Form__c WHERE Id = :ttfId];
            ttfLst.Tourist__c = acc.Id;
            update ttfLst;
            pageRef = new PageReference('/'+ttfId);
        }catch(exception ex){
            ApexPages.addMessages(ex);
        }
        return pageRef;
    }
    
    public PageReference cancelAcc(){
        PageReference pageRef = new PageReference('/'+ttfId);
        return pageRef;
    }
    
}