unpackaged/main/default/objects/Opportunity/fields/Payment_Card_Charge__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Charge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Card Charge</label>
    <referenceTo>Payment_Card_Charge__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment_Card_Charge__c/Payment_Card_Charge__c.object-meta.xml
<CustomObject>
    <label>Payment Card Charge</label>
    <nameField>
        <displayFormat>PCC-{000000}</displayFormat>
        <label>Payment Card Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Card Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment_Card_Charge__c/fields/Owning_Country__c.field-meta.xml
<CustomField>
    <fullName>Owning_Country__c</fullName>
    <label>Owning Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Owning_Country</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Owning_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Dominican Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Ecuador</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>El Salvador</fullName>
    </customValue>
    <customValue>
        <fullName>Equador</fullName>
    </customValue>
    <customValue>
        <fullName>Faroe Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>French West Indies</fullName>
    </customValue>
    <masterLabel>Owning Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/x_setOppPaymentCC.cls
public class x_setOppPaymentCC {
@InvocableMethod(label='Set Payment Card Charge' description='Set Payment Card Charge')

	public static void setPayCardCharge(list<id> listOppId)
    {
    	for(Id oppId :listOppId)
        {
        	//get Opportunity record using id from process
            Opportunity opp = [SELECT Id, Owning_Country__c, Payment_Card_Charge__c
                                   	FROM Opportunity 
                                   	WHERE Id = :oppId
                                  	LIMIT 1];
                
            //get payment charge id
            List<Payment_Card_Charge__c> lstPCC = new List<Payment_Card_Charge__c>();    
            lstPCC = [ SELECT Id, Owning_Country__c
                       FROM Payment_Card_Charge__c
                       WHERE Owning_Country__c = :opp.Owning_Country__c
                       LIMIT 1];
            
            //check if opportunity payment charge is set - update it
            if (lstPCC.size() > 0){   
                Payment_Card_Charge__c pcc = lstPCC.get(0);
                String paymentCardChargeId = pcc.Id;
                if (opp.Payment_Card_Charge__c != paymentCardChargeId){
                    opp.Payment_Card_Charge__c = paymentCardChargeId;
                    update opp;                    
                }
            }
        }
    }  
}