unpackaged/main/default/objects/OutgoingStreamingObject__c/OutgoingStreamingObject__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>OutgoingCall</label>
</CustomObject>

unpackaged/main/default/objects/OutgoingStreamingObject__c/fields/Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Status__c</fullName>
    <label>Call Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/OutgoingStreamingObject__c/fields/User_Status__c.field-meta.xml
<CustomField>
    <fullName>User_Status__c</fullName>
    <label>User Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestMttlFooterOutgoingCall.cls
@isTest
private class TestMttlFooterOutgoingCall{
    static testMethod void MttlFooterOutgoingCall()
    {
        // Insert Contacts data
        String conId;
        Contact con = new contact();
        
        con.lastname='TestRag';
        con.MailingCountry = 'United Kingdom';
        Insert con;
        // Insert custom settings data(Outgoing Call)
        OutgoingStreamingObject__c os = new OutgoingStreamingObject__c();
        os.name = 'OutgoingCall';
        os.SetupOwnerId=userinfo.getuserid();
        os.Call_Status__c='Connected';
        os.User_Status__c='Available';
        insert os; 
        
        apexpages.currentpage().getparameters().put('conId',con.id);
        Apexpages.currentPage().getParameters().Put('Name','Ragava');
       
       test.startTest(); 
       MttlFooterOutgoingCallController foc = new MttlFooterOutgoingCallController();
       List<String> conliIds=new List<String>();
       conliIds.add(con.Id);
       foc.recentviewedcontacts=conliIds;
       foc.cancelOnGoingcall();
       foc.externalcontact();
       foc.externalcontactend();
       foc.contactend();
       foc.displayBlock();
       foc.displayContact();
       foc.ConnectingBlock();
       foc.ConnectedBlock();
       foc.addNotes();
       foc.toggleSort();
       foc.runQuery();
       foc.runSearch();
       //foc.outgoingCalls('xyz','abx','ghy');
       foc.updateUserStatus();
       foc.Externalnumsearch();
        foc.addNotesexternalnumber();
        foc.contkey='TestRag';
        foc.filterContacts();
       test.stopTest();
    }
    
}